#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 13/9/2011

# Met a jour dans git.
# git remote -v
# git remote add origin  https://github.com/BrunoLafleur/pbslacks.git
# git remote set-url origin  https://github.com/BrunoLafleur/pbslacks.git
# git push -f origin master
# git push
# git push --tags -f
# git pull

# Autres exemples :
# git checkout master
# git checkout 0.11.5b
# git checkout master
# git archive -o ../kmplayer-0.11.5b.tar 0.11.5b --prefix=kmplayer-0.11.5b/

# Pour changer un commit (auteur ou autre)
# git log (choisissez le ou les commits
# git rebase -i edc6befbb08f74d9cab19703e8d31037695d36ba
# Remplacez pick par edit sur ces commits.
# git commit --amend --reset-author --no-edit
# git rebase --continue
# git checkout a4a7bb2b14f758b6bb4b180d40af884278c9300e -- builds/sbo

SAVEPROD=..
REMPNAME=$(basename "$0")

if [ "$0" != "./$REMPNAME" ] ;then
	echo "Commande a lancer dans le repertoire contenant ce script"
	echo "en tapant : ./$REMPNAME"
	exit 1
fi

MYPWD=$(pwd -P)

if [ $? -eq 1 ] ;then
    MYPWD=$(pwd)
    CDPAR=
else
    CDPAR='-P'
fi

FVERSION=version
VERSION=$(basename "$MYPWD")
XARCHIVE=$SAVEPROD/${VERSION}.git
XTAG="$(cat $FVERSION|fgrep "$VERSION"|sed 's/^.* //')"

echo "Mise a jour git et creation archive git."
echo "----------------------------------------"

find . '(' -name '*%' -o -name '*~' -o -name '#*#' -o -name '.??*%' \
    -o -name '.??*~' -o -name '.??*.swp' -o -name '.#*#' -o -name 'core' \
    -o -name 'gmon.out' ')' -user $USER -type f -exec \rm -f '{}' \;
git add .
git add -u
git commit -F $FVERSION
git tag -f "$XTAG" HEAD
git bundle create $XARCHIVE HEAD --all

echo "Creation archive tgz."
echo "---------------------"

cd $CDPAR $SAVEPROD
tar cfz ${VERSION}.tgz $VERSION

echo "Fait."
