#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xhelp () {
    cat <<EOF
Script a lancer dans le repertoire contenant packages, packages2 et al.
Launch this script in the directory including packages, packages2 et al.
EOF
}

if [ ! -d packages ] ;then
    xhelp
    exit 1
fi

SLACKSLONLY="https://slackonly.com/pub/packages/current-x86_64"
SLACKSLONLY32="https://slackonly.com/pub/packages/current-x86"

xpurgepac () {
    pac="$1"
    last=$(ls -1t "$pac"*.t?z|head -1)
    for j in "$pac"*.t?z ;do
	if [ "$j" != "$last" ] ;then
	    rm -f "$j"
	fi
    done
}

xgetpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    wget -N -A "$pac"'*.t?z' -r -nv -np -nH --cut-dir=$prof "$dir/"
}

cd packages
for i in graphics/goocanvas development/portaudio system/refind development/icoutils audio/portmidi libraries/wxPython libraries/libpng-legacy12 python/pygoocanvas ;do
    PROJ=$(echo $i|cut -d '/' -f2)
    xgetpac "$PROJ-" "$SLACKSLONLY/$i" 5
    xpurgepac "$PROJ-"
done
cd 32
for i in development/icoutils ;do
    PROJ=$(echo $i|cut -d '/' -f2)
    xgetpac "$PROJ-" "$SLACKSLONLY32/$i" 5
    xpurgepac "$PROJ-"
done
cd ../..
find packages -name 'index.html*' -exec rm -f {} \;

cd packages2
for i in office/evince libraries/libsmf multimedia/lsdvd graphics/fontforge graphics/lilypond system/t1utils ;do
    PROJ=$(echo $i|cut -d '/' -f2)
    xgetpac "$PROJ-" "$SLACKSLONLY/$i" 5
    xpurgepac "$PROJ-"
done
cd ..
find packages2 -name 'index.html*' -exec rm -f {} \;
