#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

xhelp () {
    mygt 'Launch this script in a new directory.\nor in a directory which contains slackware64-current.\n\npbslacks should be side by side of this current directory.'|sed 's@\\n@\n@g'
    echo
    echo '> ../pbslacks/pbaspire [-test (test only, no actions)] [-help|-h] [-nodial]'
}

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-test" ] ;then
	XTEST=1
    elif [ "$MYARG" = "-nodial" ] ;then
	ISDIAL=0
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

if [ $XTEST -ne 1 -a "$0" != "../pbslacks/$MYPROG" \
    -a "$0" != "pbslacks/$MYPROG" ] ;then
    xhelp
    exit 1
fi

PBNAME=$0
XTEMPOUT=$(mktemp -p /tmp -t pbaspireout.XXXXXX)
XTEMPMES=$(mktemp -p /tmp -t pbaspiremes.XXXXXX)

cleanup () {
    rm -f $XTEMPOUT
    rm -f $XTEMPMES
}

trap 'echo "*** Ctrl-C caught -- aborting operations ***"; cleanup; exit 1' 2 14 15 # trap Ctrl-C and kill

INIT=$(mygt 'Init/Verify the repository.')
CORE=$(mygt 'Get/Update versus officiel Slackware, multilib and frameworks KDE5')
ALIEN=$(mygt 'Get/Update some Alien Bob binary packages')
PONCE=$(mygt 'Get/Update some Ponce binary packages')
SLONLY=$(mygt 'Get/Update some Slackonly binary packages')
OTHER=$(mygt 'Get/Update some other source or binary packages')
MOZILLA=$(mygt 'Get/Update latest Firefox and Thunderbird')

xmaster () {
    defitem=$1;shift
    xsel1=$1;shift;xsel2=$1;shift;xsel3=$1;shift;xsel4=$1;shift;xsel5=$1;shift
    xsel6=$1;shift;xsel7=$1
    pactit=$(mygt 'Main menu');pactit="pbaspire: $pactit"
    pactxt=$(mygt 'Choose your actions below')
    if [ $ISDIAL -eq 1 ] ;then
	dialog --colors --title "$pactit" --default-item $defitem \
	    --defaultno --separate-output --item-help --help-button \
	    --help-status --checklist "$pactxt" 0 100 7 \
	    init "$INIT" $xsel1 init \
	    core "$CORE" $xsel2 core \
	    alien "$ALIEN" $xsel3 alien \
	    ponce "$PONCE" $xsel4 ponce \
	    slonly "$SLONLY" $xsel5 slonly \
	    other "$OTHER" $xsel6 other \
	    mozilla "$MOZILLA" $xsel7 mozilla
    else
	echo '------------------------------------'
	echo "        $pactit"
	echo '------------------------------------'
	echo "HELP (y or n) :";read c
	if [ "$c" = "y" ] ;then
	    echo "HELP init (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP init" 1>&2;return;fi
	    echo "HELP core (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP core" 1>&2;return;fi
	    echo "HELP alien (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP alien" 1>&2;return;fi
	    echo "HELP ponce (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP ponce" 1>&2;return;fi
	    echo "HELP slonly (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP slonly" 1>&2;return;fi
	    echo "HELP other (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP other" 1>&2;return;fi
	    echo "HELP mozilla (y or n) :";read c
	    if [ "$c" = "y" ] ;then echo "HELP mozilla" 1>&2;return;fi
	fi
	echo "$INIT (y or n) :";read c
	[ "$c" = "y" ] && echo "init" 1>&2
	echo "$CORE (y or n) :";read c
	[ "$c" = "y" ] && echo "core" 1>&2
	echo "$ALIEN (y or n) :";read c
	[ "$c" = "y" ] && echo "alien" 1>&2
	echo "$PONCE (y or n) :";read c
	[ "$c" = "y" ] && echo "ponce" 1>&2
	echo "$SLONLY (y or n) :";read c
	[ "$c" = "y" ] && echo "slonly" 1>&2
	echo "$OTHER (y or n) :";read c
	[ "$c" = "y" ] && echo "other" 1>&2
	echo "$MOZILLA (y or n) :";read c
	[ "$c" = "y" ] && echo "mozilla" 1>&2
    fi
}

xsel="on on on on on on on on"
ditem=init
bclaide=1

while [ $bclaide -eq 1 ] ;do
    xmaster $ditem $xsel 2> $XTEMPOUT
    bclaide=$(cat $XTEMPOUT|grep '^HELP'|wc -l)
    if [ $bclaide -eq 1 ] ;then
	xitem="$(cat $XTEMPOUT|grep '^HELP'|cut -d ' ' -f2)"
	xsel=
	for i in init core alien ponce slonly other mozilla ;do
	  if [ $(grep "^$i$" "$XTEMPOUT"|wc -l) -eq 1 ] ;then
	      xsel="$xsel on"
	  else
	      xsel="$xsel off"
	  fi
	done
	ditem=$xitem;bclaide=1;pacaide=
	if [ "$xitem" = init ] ;then
	    pacaide=$(mygt 'Initialize or verify the current repository.')
	elif [ "$xitem" = core ] ;then
	    pacaide=$(mygt 'Get or update the officiel lastest current Slackware.\nAnd the multilib of Alien Bob which is a 32 bits compatibility set of packages.\nAnd the frameworks libraries of Kde5 offered by Alien Bob.')
	elif [ "$xitem" = alien ] ;then
	    pacaide=$(mygt 'Get or update some Alien Bob binary packages.')
	elif [ "$xitem" = ponce ] ;then
	    pacaide=$(mygt 'Get or update some Ponce binary packages.')
	elif [ "$xitem" = slonly ] ;then
	    pacaide=$(mygt 'Get or update some Slackonly binary packages.')
	elif [ "$xitem" = other ] ;then
	    pacaide=$(mygt 'Get or update some other source or binary packages.')
	elif [ "$xitem" = mozilla ] ;then
	    pacaide=$(mygt 'Get or update Firefox and Thunderbird.')
	fi
	if [ $ISDIAL -eq 1 ] ;then
	    dialog --colors --title "$xitem" --msgbox "$pacaide" 20 80
	else
	    echo '------------------------------------'
	    echo "          $xitem"
	    echo '------------------------------------'
	    echo "$pacaide"|sed 's@\\n@\n@g'
	fi
    fi
done

while read i;test "$i" != "" ;do
    if [ "$(echo $i|cut -c1-4)" = 'HELP' ] ;then
	continue
    elif [ "$i" = init ] ;then
	[ $XTEST -ne 1 ] && "$PBNAME"init
	emygt "Initialisation done : \Z3\${PBNAME}init\Zn." >> $XTEMPMES
    elif [ "$i" = core ] ;then
	[ $XTEST -ne 1 ] && "$PBNAME"core
	emygt "Get/Upgrade core system done : \Z3\${PBNAME}core\Zn." >> $XTEMPMES
    elif [ "$i" = alien ] ;then
	[ $XTEST -ne 1 ] && "$PBNAME"alien
	emygt "Get/Upgrade Alien Bob packages done : \Z3\${PBNAME}alien\Zn." \
	    >> $XTEMPMES
    elif [ "$i" = ponce ] ;then
        [ $XTEST -ne 1 ] && "$PBNAME"ponce
	emygt "Get/Upgrade Ponce packages done : \Z3\${PBNAME}ponce\Zn." >> $XTEMPMES
    elif [ "$i" = slonly ] ;then
	[ $XTEST -ne 1 ] && "$PBNAME"slonly
	emygt "Get/Upgrade Slackonly packages done : \Z3\${PBNAME}slonly\Zn." \
	    >> $XTEMPMES
    elif [ "$i" = other ] ;then
	[ $XTEST -ne 1 ] && "$PBNAME"other
	emygt "Get/Upgrade other source or binary packages done : \Z3\${PBNAME}other\Zn." >> $XTEMPMES
    elif [ "$i" = mozilla ] ;then
	[ $XTEST -ne 1 ] && "$PBNAME"moz -lang fr
	emygt "Get/Upgrade Firefox and Thunderbird done : \Z3\${PBNAME}mozilla\Zn." \
	    >> $XTEMPMES
    fi
done < $XTEMPOUT

rm -f $XTEMPOUT

if [ ! -f "$XTEMPMES" -o $(cat "$XTEMPMES"|wc -c) -eq 0 ] ;then
    mygt "No action was demanded. Exit." > $XTEMPMES
fi

DACTION=$(mygt 'Actions which were done')

if [ $ISDIAL -eq 1 ] ;then
    dialog --colors --title "$DACTION" --msgbox "$(cat $XTEMPMES)" 20 90
else
    nodialog "$DACTION" $XTEMPMES
fi

rm -f $XTEMPMES
