#! /bin/sh

if [ ! -d packages ] ;then
    echo "Script a lancer dans le repertoire contenant packages, packages2 et al."
    exit 1
fi

SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware'
SLACKALIEN="$SLACKMIR/people/alien/slackbuilds"
SLACKALIEN2="$SLACKMIR/people/alien-kde/current/latest/x86_64/deps"

xpurgepac () {
    pac="$1"
    LAST=`ls -1t "$pac"*.t?z|head -1`
    for j in "$pac"*.t?z ;do
	if [ "$j" != "$LAST" ] ;then
	    rm -f "$j"
	fi
    done
}

xgetpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    wget -N -A "$pac"'*.t?z' -r -np -nH --cut-dir=$prof "$dir/"
}

cd packages
for i in cabextract jack2 libxkbcommon mlt musescore openjdk qt5 qt5-speech ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg64/current" 10
    xpurgepac "$i-"
done
for i in mlt ;do
    xgetpac "$i-" "$SLACKALIEN2" 10
    xpurgepac "$i-"
done
for i in steamclient ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg/current" 10
    xpurgepac "$i-"
done
for i in libreoffice libreoffice-dict-fr libreoffice-l10n-fr libreoffice-sdkdoc ;do
    xgetpac "$i-"'[0-9]' "$SLACKALIEN/libreoffice/pkg64/current" 10
    xpurgepac "$i-"'[0-9]'
done
cd 32
for i in cabextract ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg/current" 10
    xpurgepac "$i-"
done
cd ../..
find packages -name 'index.html*' -exec rm -f {} \;

cd packages2
for i in SDL_sound aubio rubberband vlc ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg64/current" 10
    xpurgepac "$i-"
done
cd ..
find packages2 -name 'index.html*' -exec rm -f {} \;

cd packages3
for i in calibre ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg64/current" 10
    xpurgepac "$i-"
done
cd ..
find packages3 -name 'index.html*' -exec rm -f {} \;

cd packages4
for i in chromium ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg64/current" 10
    xpurgepac "$i-"
done
for i in PyQt5 wayland-protocols ;do
    xgetpac "$i-" "$SLACKALIEN2" 10
    xpurgepac "$i-"
done
cd audacity
for i in audacity lilv lv2 serd sord sratom suil vamp-plugin-sdk ;do
    xgetpac "$i-" "$SLACKALIEN/$i/pkg64/current" 10
    xpurgepac "$i-"
done
cd ../..
find packages4 -name 'index.html*' -exec rm -f {} \;
