#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# can be done non root.

XDIR="$(dirname $0)"
MYPWD=$(pwd)
. "$XDIR/pbinclude"
if [ "$PBARCH" = x64 ] ;then
    . "$XDIR/pbaspireinit"
else
    . "$XDIR/pbaspirearminit"
fi
. "$XDIR/pbaspireinc"

xhelp () {
    mygt 'Launch this script in a directory which contains gdm.'
    echo
    echo '> ../pbslacks/pbaspiregdm [-help|-h]'
}

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

if [ ! -d gdm -o \
       \( "$0" != "../pbslacks/$MYPROG" -a "$0" != "pbslacks/$MYPROG" \) ] ;then
    xhelp
    exit 1
fi

[ $PBARCH = arm ] && AARCH=arm || AARCH=64

# GDM
(
    cd gdm
    for i in libart_lgpl libgnomecanvas gdm xvkbd ;do
	xgetsbosrc $i
    done
)
if [ -d slackware$AARCH-current ] ;then
    (
	cd slackware$AARCH-current
	ln -sf ../gdm .
    )
fi
