#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
. "$XDIR/pbaspireinit"
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"
. "$XDIR/pbpathinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
}

if [ ! -d packages ] ;then
    xhelp
    exit 1
fi

############################################
# Download new versions of binary packages.
# Alien Bob packages.
############################################
xgeturl "$SLACKALIEN/GPG-KEY"
mv -f GPG-KEY gpgkeys/GPG-KEY-slackbuilds-alien

(
    cd packages
    for i in cabextract jack2 musescore openjdk boost-compat wine ;do
	xgetpac "$i" "$SLACKALIEN/$i/pkg64/current" 10
    done
    rm -f libxkbcommon-*
    rm -f qt5-*

    # MLT pour openshot. On recompile pour dependances jackrack, rubberband, swfdec.
    i=mlt
    xgetsrcpac "$i" "$SLACKALIENSRC2/$i/" 9
    
    for i in steamclient ;do
	xgetpac "$i" "$SLACKALIEN/$i/pkg/current" 10
    done
    for i in libreoffice libreoffice-dict-fr libreoffice-l10n-fr \
			 libreoffice-sdkdoc ;do
	xgetpac "$i" "$SLACKALIEN/libreoffice/pkg64/current" 10
    done
    (
	cd 32
	for i in cabextract ;do
	    xgetpac "$i" "$SLACKALIEN/$i/pkg/current" 10
	done
    )
)
xpurgeindex packages

############################################
(
    cd packages2
    for i in SDL_sound aubio rubberband vlc ;do
	xgetpac "$i" "$SLACKALIEN/$i/pkg64/current" 10
    done
)
xpurgeindex packages2

############################################
(
    cd packages3
    for i in calibre ;do
	xgetpac "$i" "$SLACKALIEN/$i/pkg64/current" 10
    done
)
xpurgeindex packages3

############################################
(
    cd packages4
    for i in chromium-widevine-plugin nodejs wxGTK ;do
	xgetpac "$i" "$SLACKALIEN/$i/pkg64/current" 10
    done
    rm -f PyQt5-*

    [ -f chromium/chromium.SlackBuild ] && \
	mv -f chromium/chromium.SlackBuild chromium/chromium.SlackBuild.bak
    for i in chromium wxGTK3 ;do
	xgetsrcpac0 "$i" "$SLACKALIEN/$i/build" 9
    done
    
    [ ! -d audacity ] && mkdir audacity
    (
	cd audacity
	for i in audacity lilv lv2 serd sord sratom suil vamp-plugin-sdk ;do
	    xgetsrcpac0 "$i" "$SLACKALIEN/$i/build" 9
	done
    )
    
    [ ! -d ardour ] && mkdir ardour
    (
	cd ardour
	for i in liblo liblrdf ardour ;do
	    xgetsrcpac0 "$i" "$SLACKALIEN/$i/build" 9
	done
    )
)
xpurgeindex packages4
