#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

if [ ! -d packages ] ;then
    echo "Script a lancer dans le repertoire contenant packages, packages2 et al."
    echo "Launch this script in the directory including packages, packages2 et al."
    exit 1
fi

SLACKPONCE="http://ponce.cc/slackware/slackware64-current/packages"
SLACKPONCE32="http://ponce.cc/slackware/slackware-current/packages"

xpurgepac () {
    pac="$1"
    last=`ls -1t "$pac"*.t?z|head -1`
    for j in "$pac"*.t?z ;do
	if [ "$j" != "$last" ] ;then
	    rm -f "$j"
	fi
    done
}

xgetpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    wget -N -A "$pac"'*.t?z' -r -nv -np -nH --cut-dir=$prof "$dir/"
}

cd packages
for i in ladspa_sdk swfdec x264 libdvdcss vid.stab ;do
    xgetpac "$i-" "$SLACKPONCE" 3
    xpurgepac "$i-"
done
cd 32
for i in libdvdcss ;do
    xgetpac "$i-" "$SLACKPONCE32" 3
    xpurgepac "$i-"
done
cd ../..

cd packages2
for i in gtksourceview3 ;do
    xgetpac "$i-" "$SLACKPONCE" 3
    xpurgepac "$i-"
done
cd ..

cd packages3
for i in graphviz ;do
    xgetpac "$i-" "$SLACKPONCE" 3
    xpurgepac "$i-"
done
cd ..

cd packages4
for i in hdf5 numpy ;do
    xgetpac "$i-" "$SLACKPONCE" 3
    xpurgepac "$i-"
done
if [ ! -d audacity ] ;then
    mkdir audacity
fi
cd audacity
for i in celt051 ;do
    xgetpac "$i-" "$SLACKPONCE" 3
    xpurgepac "$i-"
done
cd ../..

rm -f packages*/robots.txt*
rm -f packages*/*/robots.txt*
