#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

test_oldslack () {
    pac="$1"
    par=$(dirname "$pac");cur=$(pwd);rcur=$par/$(basename "$cur")
    last=$(ls -1td "$pac"[0-9]* 2> /dev/null |head -1)

    if [ "$last" = "$rcur" ] ;then
	ls -1td "$pac"[0-9]* 2> /dev/null |head -2|tail -1
    else
	echo "$last"
    fi
}

OLDSLACK=$(test_oldslack ../Slackware-x64-)

if [ ! -d packages -a -d "$OLDSLACK" ] ;then
    echo "OLDSLACK = $OLDSLACK"
    echo "Copies of $OLDSLACK/packages* and bumblebee will be done."
    echo "Else all add-on packages will be downloaded again."

    cp -a "$OLDSLACK/packages"* .
    if [ -d "$OLDSLACK/divers" ] ;then
	cp -a "$OLDSLACK/divers" .
	mv divers bumblebee
    else	
	cp -a "$OLDSLACK/bumblebee" .
    fi
fi

# This project.
if [ ! -h pbslacks ] ; then
    ln -s ../pbslacks .
fi

# Some specifics tunings.
if [ ! -h perso ] ; then
    if [ -d ../perso ] ;then
        ln -s ../perso .
    else
	mkdir perso
    fi
fi

# MPlayer Skins (to download).
if [ ! -h divers ] ; then
    if [ -d ../divers ] ;then
        ln -s ../divers .
    else
	mkdir divers
    fi
fi

if [ ! -d packages ] ;then
    mkdir packages
    mkdir packages/32
    mkdir packages/compat32
    mkdir packages/Mozilla
fi
if [ ! -d packages2 ] ;then
    mkdir packages2
fi
if [ ! -d packages3 ] ;then
    mkdir packages3
fi
if [ ! -d packages4 ] ;then
    mkdir packages4
fi
if [ ! -d bumblebee ] ;then
    mkdir bumblebee
    mkdir bumblebee/Crazybee
    cp pbslacks/builds/crazybee.sh bumblebee/Crazybee
fi
