#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# Function for purge html index.
xpurgeindex () {
    dir="$1"
    find "$dir" -name 'index.html*' -exec rm -f {} \;
    rm -f "$dir/robots.txt"*
    rm -f "$dir/"*"/robots.txt"*
}

# Function for purge old packages.
xpurgepac () {
    pac="$1"
    suf="$2"
    last=$(ls -1t ${pac}*.$suf 2> /dev/null|head -1)
    for j in $(ls ${pac}*.$suf 2> /dev/null) ;do
	if [ "$j" != "$last" ] ;then
	    emygt "Delete : \$j"
	    rm -f "$j"
	fi
    done
}

# Get new version of a package in a repository.
xgetpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    echo '------------------------------------'
    emygt "Package \$pac :"
    wget -N -A "$pac"'-[0-9]*.t?z*' -r -nv -np -nH --cut-dir=$prof "$dir/"
    xpurgepac "$pac-[0-9]" t?z
    xpurgepac "$pac-[0-9]" t?z.asc
    xpurgepac "$pac-[0-9]" t?z.md5
    xpurgepac "$pac-[0-9]" t?z.sha256
}

# Get the original tarball with the slack build scripts.
xgetsrcpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    wget -N -r -nv -np -nH --cut-dir=$prof "$dir/"
}

xgetsrcpac0 () {
    pac="$1"
    dir="$2"
    prof="$3"
    mkdir -p "$pac"
    (
	cd "$pac"
	xgetsrcpac "$pac" "$dir" $prof
    )
}

# Get a local copie of the original tarball with the slack build scripts.
xlocalsrcpac () {
    name="$1"
    path="$2"
    [ ! -d "$name" ] && mkdir "$name"
    cp -u "../pbslacks/builds/${name}.tar.gz" "$name"
    if [ "$path" != '' ] ;then
      	emygt "Local copy of ../pbslacks/builds/\$path to \$name"
    	cp "../pbslacks/builds/$path" "$name"
    fi
}

# Get static url.
xgeturl () {
    path="$1"
    wget -N -nv --content-disposition "$path"
}

# Get the original source tarball.
xgetsrc () {
    name="$1"
    path="$2"
    [ ! -d "$name" ] && mkdir "$name"
    cp -u "../pbslacks/builds/${name}.tar.gz" "$name"
    (
	cd "$name"
	xgeturl "$path"
	# For queries names.
	find . -name '*.t*z\?*'|while read i;test "$i" != "" ;do
	    j="$(echo "$i"|cut -d '?' -f1)"
	    mv "$i" "$j"
	done
    )
}

# Get the original source tarball with path in package.info.
xgetsbosrc () {
    name="$1"
    tar xfz ../pbslacks/builds/${name}.tar.gz $name/${name}.info
    path=$(cat $name/${name}.info | fgrep DOWNLOAD_x86_64|cut -d '=' -f2|cut -d '"' -f2)
    [ -z "$path" ] && path=$(cat $name/${name}.info | fgrep DOWNLOAD|cut -d '=' -f2|cut -d '"' -f2)
    rm -f $name/${name}.info
    xgetsrc $name "$path"
}
