#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
. "$XDIR/pbaspireinit"
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"
. "$XDIR/pbpathinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
}

if [ ! -d packages ] ;then
    xhelp
    exit 1
fi

############################################
# Download new versions of binary packages.
# Slonly packages.
############################################
(
    cd packages
    for i in graphics/goocanvas development/portaudio system/refind development/icoutils audio/portmidi libraries/wxPython libraries/libpng-legacy12 python/pygoocanvas ;do
	PROJ=$(echo $i|cut -d '/' -f2)
	xgetpac "$PROJ-" "$SLACKSLONLY/$i" 5
    done
    (
	cd 32
	for i in development/icoutils ;do
	    PROJ=$(echo $i|cut -d '/' -f2)
	    xgetpac "$PROJ-" "$SLACKSLONLY32/$i" 5
	done
    )
)
xpurgeindex packages

############################################
(
    cd packages2
    for i in office/evince libraries/libsmf multimedia/lsdvd graphics/fontforge graphics/lilypond system/t1utils ;do
	PROJ=$(echo $i|cut -d '/' -f2)
	xgetpac "$PROJ-" "$SLACKSLONLY/$i" 5
    done
)
xpurgeindex packages2
