#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# can be done non root.

MYPWD=$(pwd)
export HOMESLACK="$MYPWD"
SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware'
SLACKMULTI="$SLACKMIR/people/alien/multilib/current"
SLACKKDEFW="$SLACKMIR/people/alien-kde/current/latest/x86_64/kde/frameworks"
GPARTEDISO="https://downloads.sourceforge.net/gparted/gparted-live-1.0.0-5-amd64.iso"

# Function for getting packages.
myrget () {
    prof=$1
    gpath="$2"
    pack="$3"
    wget -N -nv -np -nH --cut-dirs=$prof -r "$gpath/"
    [ -d "$pack" ] && find "$pack" -name 'index.html*' -exec rm -f {} \;
}

# Function for purge old packages.
xpurgepac () {
    pac="$1"
    suf="$2"
    last=$(ls -1t ${pac}*.$suf|head -1)
    for j in ${pac}*.$suf ;do
	if [ "$j" != "$last" ] ;then
	    echo "Delete : $j"
	    rm -f "$j"
	fi
    done
}

myrget 4 "$SLACKMIR/slackware64-current" slackware64-current

# Nettoyage des doublons
echo '------------------------------------'
if [ -d slackware64-current ] ;then
    cd slackware64-current
    find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
        pack=$(echo $i|sed 's@-[0-9].*$@@')
        xpurgepac "$pack-[0-9]" txt
        xpurgepac "$pack-[0-9]" t?z
        xpurgepac "$pack-[0-9]" asc
    done
    ln -sf ../current .
    ln -sf ../perso .
    ln -sf ../pbslacks .
    ln -sf ../bumblebee .
    ln -sf ../divers .
    ln -sf ../packages* .
    cd ..
    echo "Copie Slackware current faite."
else
    echo "Copie Slackware current non faite."
fi
echo '------------------------------------'

# Multilib Alien Bob.
# can be done non root.
myrget 7 "$SLACKMULTI" current

# Nettoyage des doublons
echo '------------------------------------'
if [ -d current ] ;then
    cd current
    find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
        pack=$(echo $i|sed 's@-[0-9].*$@@')
        xpurgepac "$pack-[0-9]" lst
        xpurgepac "$pack-[0-9]" meta
        xpurgepac "$pack-[0-9]" txt
        xpurgepac "$pack-[0-9]" t?z
        xpurgepac "$pack-[0-9]" asc
        xpurgepac "$pack-[0-9]" md5
    done
    cd ..
    echo "Copie Slackware multilib faite."
else
    echo "Copie Slackware multilib non faite."
fi
echo '------------------------------------'

# Frameworks KDE5 Alien Bob
[ ! -d packages4 ] && mkdir packages4

cd packages4
myrget 10 "$SLACKKDEFW" frameworks

# Nettoyage des doublons
echo '------------------------------------'
if [ -d frameworks ] ;then
    cd frameworks
    find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
	pack=$(echo $i|sed 's@-[0-9].*$@@')
	xpurgepac "$pack-[0-9]" lst
	xpurgepac "$pack-[0-9]" meta
	xpurgepac "$pack-[0-9]" txt
	xpurgepac "$pack-[0-9]" t?z
	xpurgepac "$pack-[0-9]" asc
	xpurgepac "$pack-[0-9]" md5
    done
    cd ..
    echo "Copie alien KDE5 frameworks faite."
else
    echo "Copie alien KDE5 frameworks non faite."
fi
echo '------------------------------------'
cd ..

# GParted
if [ ! -h Linuxiso ] ; then
    [ ! -d ../Linuxiso ] && mkdir ../Linuxiso
    ln -s ../Linuxiso .
fi
cd Linuxiso
LGPARTEDISO=$(basename "$GPARTEDISO")
if [ ! -f "$LGPARTEDISO" ] ;then
    wget -N -nv --content-disposition "$GPARTEDISO"
    echo '------------------------------------'
    if [ -f "$GPARTEDISO" ] ;then
	echo "Copie GParted faite."
    else
	echo "Copie GParted non faite."
    fi
    echo '------------------------------------'
fi
cd ..
