#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
. "$XDIR/pbaspireinit"
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"
. "$XDIR/pbpathinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
    echo
    echo '> ../pbslacks/$MYPROG'
}

if [ ! -d packages -o \
       \( "$0" != "../pbslacks/$MYPROG" -a "$0" != "pbslacks/$MYPROG" \) ] ;then
    xhelp
    exit 1
fi

############################################
# Download new versions of binary packages.
# Conrad and Slonly packages.
############################################
if [ ! -f  gpgkeys/GPG-KEY-x64-conraid ] ;then
    xgeturl "$SLACKCF/GPG-KEY"
    mv -f GPG-KEY gpgkeys/GPG-KEY-x64-conraid
fi
if [ ! -f gpgkeys/GPG-KEY-x64-slackel ] ;then
    xgeturl "$SLACKDJPAR/GPG-KEY"
    mv -f GPG-KEY gpgkeys/GPG-KEY-x64-slackel
fi
if [ ! -f gpgkeys/GPG-KEY-x32-slackel ] ;then
    xgeturl "$SLACKDJPAR32/GPG-KEY"
    mv -f GPG-KEY gpgkeys/GPG-KEY-x32-slackel
fi

(
    cd packages
    for i in gimp-script-fu x265 skypeforlinux-bin podofo scribus ;do
	xgetpac "$i" "$SLACKCF/$i" 3
    done
    [ ! -d openshot ] && mkdir openshot
    (
	cd openshot
	for i in dos2unix double-conversion potrace gdl graphicsmagick ;do
	    xgetpac "$i" "$SLACKCF/$i" 3
	done
	for i in libvdpau-va-gl ;do
	    xgetpac "$i" "$SLACKDJ" 5
	done
    )
    (
	cd 32
	xgetpac python2 "$SLACKMIR/slackware-${SLACKVER}/slackware/d" 7
    )
)
xpurgeindex packages

############################################
(
    cd packages2
    for i in jq lua lua53 oniguruma valgrind ;do
	xgetpac "$i" "$SLACKCF/$i" 3
    done
    for i in guile1.8 ;do
	xgetpac "$i" "$SLACKDJ" 5
    done
    # For Lutris (game manager)
    for i in gnome-desktop webkitgtk libseccomp ;do
	xgetpac "$i" "$SLACKDL" 4
    done
)
xpurgeindex packages2

############################################
(
    cd packages4
    for i in exiftool unrar ;do
	xgetpac "$i" "$SLACKCF/$i" 3
    done
    for i in xcftools ;do
	xgetpac "$i" "$SLACKDJ" 5
    done
    [ ! -d tesseract4 ] && mkdir tesseract4
    (
	cd tesseract4
	for i in leptonica tesseract ;do
	    xgetpac "$i" "$SLACKCF/$i" 3
	done
    )
)
cp pbslacks/builds/tesseract4/* packages4/tesseract4
xpurgeindex packages4
