#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# Function for purge html index.
xpurgeindex () {
    dir="$1"
    find "$dir" -name 'index.html*' -exec rm -f {} \;
    rm -f "$dir/robots.txt"*
    rm -f "$dir/"*"/robots.txt"*
}

# Function for purge old packages.
xpurgepac () {
    pac="$1"
    suf="$2"
    last=$(ls -1t ${pac}*.$suf 2> /dev/null|head -1)
    for j in $(ls ${pac}*.$suf 2> /dev/null) ;do
	if [ "$j" != "$last" ] ;then
	    emygt "Delete : \$j"
	    rm -f "$j"
	fi
    done
}

# Get new version of a package in a repository.
xgetpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    echo '------------------------------------'
    emygt "Package \$pac :"
    wget -N -A "$pac"'*.t?z' -r -nv -np -nH --cut-dir=$prof "$dir/"
    xpurgepac "$pac" t?z
}

# Get the original tarball with the slack build scripts.
xgetsrcpac () {
    pac="$1"
    dir="$2"
    prof="$3"
    wget -N -r -nv -np -nH --cut-dir=$prof "$dir/"
}

# Get a local copie of the original tarball with the slack build scripts.
xlocalsrcpac () {
    name="$1"
    path="$2"
    [ ! -d "$name" ] && mkdir "$name"
    cp -u "../pbslacks/builds/${name}.tar.gz" "$name"
    if [ "$path" != '' ] ;then
      	emygt "Local copy of ../pbslacks/builds/\$path to \$name"
    	cp "../pbslacks/builds/$path" "$name"
    fi
}

# Get the original source tarball.
xgetsrc () {
    name="$1"
    path="$2"
    [ ! -d "$name" ] && mkdir "$name"
    cp -u "../pbslacks/builds/${name}.tar.gz" "$name"
    cd "$name"
    wget -N -nv --content-disposition "$path"
    cd ..
}

# Get the original source tarball.
xgetsbosrc () {
    name="$1"
    [ ! -d "$name" ] && mkdir "$name"
    cp -u "../pbslacks/builds/${name}.tar.gz" "$name"
    cd "$name"
    tar xfz ${name}.tar.gz $name/${name}.info
    path=$(cat $name/${name}.info | fgrep DOWNLOAD_x86_64|cut -d '=' -f2|cut -d '"' -f2)
    [ -z "$path" ] && path=$(cat $name/${name}.info | fgrep DOWNLOAD|cut -d '=' -f2|cut -d '"' -f2)
    rm -f $name/${name}.info;rmdir $name
    wget -N -nv --content-disposition "$path"
    cd ..
}

# Get static url.
xgeturl () {
    path="$1"
    wget -N -nv --content-disposition "$path"
}
