#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"
. "$(dirname $0)/pbaspireinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
}

if [ ! -d packages/Mozilla ] ;then
    xhelp
    exit 1
fi

XLANG=fr

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-lang" ] ;then
	shift
	XLANG="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

XFIREFOX="https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang="
XTHUNDERBIRD="https://download.mozilla.org/?product=thunderbird-latest-SSL&os=linux64&lang="

cd packages/Mozilla
wget -N -nv --content-disposition "${XFIREFOX}$XLANG"
xpurgepac 'firefox-' tar.bz2

wget -N -nv --content-disposition "${XTHUNDERBIRD}$XLANG"
xpurgepac 'thunderbird-' tar.bz2
