#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
. "$XDIR/pbaspireinit"
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
}

if [ ! -d packages ] ;then
    xhelp
    exit 1
fi

# Sources packages.

PATHPYTHONPIL="https://github.com/python-pillow/Pillow/archive/6.2.2.tar.gz"
PATHGUILE22="https://ftp.gnu.org/gnu/guile/guile-2.2.6.tar.xz"
PATHDENEMO="http://git.savannah.gnu.org/cgit/denemo.git/snapshot/denemo-master.tar.gz"
PATHGRAMPS="https://github.com/gramps-project/gramps/archive/v5.1.1.zip"
PATHOPENAL="https://www.openal-soft.org/openal-releases/openal-soft-1.20.1.tar.bz2"
PATHLIBTXC_DXTN="https://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.bz2"
PATHLIBGAMINGGEAR="https://downloads.sourceforge.net/libgaminggear/libgaminggear-0.15.1.tar.bz2"
PATHKMPLAYER="https://anongit.kde.org/kmplayer.git"
PATHBSDDB3="https://files.pythonhosted.org/packages/e9/fc/ebfbd4de236b493f9ece156f816c21df0ae87ccc22604c5f9b664efef1b9/bsddb3-6.2.6.tar.gz"
PATHDB53="http://deb.debian.org/debian/pool/main/d/db5.3/db5.3_5.3.28+dfsg1.orig.tar.xz"
PATHDB53BIS="http://deb.debian.org/debian/pool/main/d/db5.3/db5.3_5.3.28+dfsg1-0.6.debian.tar.xz"
PATHPYICU="https://files.pythonhosted.org/packages/77/a2/7c22b63c3cab7e41cbf4a930b033f5fc3e47bc5b6b673020f5ba58cecdf2/PyICU-2.4.1.tar.gz"
PATHXRDP="https://github.com/neutrinolabs/xrdp/releases/download/v0.9.12/xrdp-0.9.12.tar.gz"
PATHXORGXRDP="https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.2.12/xorgxrdp-0.2.12.tar.gz"
PATHSFML="https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip"
PATHWXGTK3="https://github.com/wxWidgets/wxWidgets/archive/v3.0.4/wxWidgets-3.0.4.tar.gz"
PATHVBAM="https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.1.4/visualboyadvance-m-2.1.4.tar.gz"
PATHFBIDA="https://www.kraxel.org/releases/fbida/fbida-2.14.tar.gz"
PATHOPENCV="https://github.com/opencv/opencv/archive/4.1.1/opencv-4.1.1.tar.gz"
PATHOPENCVBIS="https://github.com/opencv/opencv_contrib/archive/4.1.1/opencv_contrib-4.1.1.tar.gz"
PATHDISCORD="https://discordapp.com/api/download?platform=linux&format=tar.gz"
PATHVLCYOUTUBE="https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua"
PATHMLT="https://github.com/mltframework/mlt/archive/v6.20.0.tar.gz"
PATHLIBCACA="http://caca.zoy.org/files/libcaca/libcaca-0.99.beta19.tar.gz"
PATHLIBWEBP="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz"

############################################
# Download new sources.
############################################
(
    cd packages
    xgetsrc python2-mlt "$PATHMLT"
    xgetsrc python2-libcaca "$PATHLIBCACA"
    xgetsrc python2-libwebp "$PATHLIBWEBP"
    xgetsrc openal-soft "$PATHOPENAL"
    xgetsrc libtxc_dxtn "$PATHLIBTXC_DXTN"
    xgetsrc libgaminggear "$PATHLIBGAMINGGEAR"
    xlocalsrcpac acpibrightness ""
    # python-pillow6 : re-add python2.7 support for openshot.
    # Pillow 7 from current Slackware drop support of python2.
    xgetsrc python-pillow6 "$PATHPYTHONPIL"
    rm -f python-pillow-[0-9]*.t?z
)

############################################
(
    cd packages2
    xgetsbosrc roccat-tools
    xlocalsrcpac kmplayer "kmplayer_0.11.5b.tar.bz2"
    xgetsrc denemo "$PATHDENEMO"
    # Guile 2.2 supprime en janvier. Utile a denemo.
    xgetsrc guile2.2 "$PATHGUILE22"
    # Discord just being put here. No packages done for now.
    xgeturl "$PATHDISCORD"
    xgeturl "$PATHVLCYOUTUBE"
    xpurgepac discord tar.gz
)

############################################
(
    cd packages3
    xgetsrc bsddb3 "$PATHBSDDB3"
    xgetsrc db53 "$PATHDB53"
    xgetsrc db53 "$PATHDB53BIS"
    xgetsrc pyicu "$PATHPYICU"
    xgetsrc gramps "$PATHGRAMPS"
)

############################################
(
    cd packages4
    xgetsrc xrdp "$PATHXRDP"
    xgetsrc xorgxrdp "$PATHXORGXRDP"
    xgetsrc SFML "$PATHSFML"
    xgetsrc wxGTK3 "$PATHWXGTK3"
    xgetsrc vbam "$PATHVBAM"
    xgetsrc fbida "$PATHFBIDA"
    xgetsrc opencv "$PATHOPENCV"
    xgetsrc opencv "$PATHOPENCVBIS"
    for i in kaffeine gradle audiveris signal-desktop vokoscreen ;do
	xgetsbosrc "$i"
    done
)

