#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
MYPWD=$(pwd)
PBARCH="$(basename "$MYPWD"|cut -d '-' -f2)"
if [ "$PBARCH" = x64 ] ;then
    . "$XDIR/pbaspireinit"
else
    . "$XDIR/pbaspirearminit"
fi
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"

xhelp () {
    mygt 'Launch this script in the directory including debian.'
    echo
    echo '> ../pbslacks/$MYPROG'
}

if [ ! -d debian -o \
       \( "$0" != "../pbslacks/$MYPROG" -a "$0" != "pbslacks/$MYPROG" \) ] ;then
    xhelp
    exit 1
fi

XLANG=$(echo $LANG|cut -d '.' -f1|cut -d '_' -f1)

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-lang" ] ;then
	shift
	XLANG="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

[ $PBARCH = arm ] && RARCH=arm || RARCH=x86_64

(
    # We put those in package4.
    if [ -d packages/Mozilla/thunderbird ] ;then
	rm -rf packages/Mozilla/libffi6*
	rm -rf packages/Mozilla/libevent6*
	rm -rf packages/Mozilla/thunderbird*
	rm -rf packages/Mozilla/firefox*
    fi
    cd debian
    for i in thunderbird firefox chromium ;do
	xgetsbosrc $i $RARCH
	xpurgepac "$i/$i_" deb
    done
    for i in libffi6 libevent6 libwebp6 icu4c67 ;do
	xgetsbosrc $i
    done
    
)
if [ -d slackware$PBARCH-current ] ;then
    (
	cd slackware$PBARCH-current
	ln -sf ../debian .
    )
fi
