#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
. "$XDIR/pbinclude"
if [ "$PBARCH" = x64 ] ;then
    . "$XDIR/pbaspireinit"
else
    . "$XDIR/pbaspirearminit"
fi
. "$XDIR/pbaspireinc"
. "$XDIR/pbpathinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
    echo
    echo '> ../pbslacks/$MYPROG'
}

if [ ! -d packages -o \
       \( "$0" != "../pbslacks/$MYPROG" -a "$0" != "pbslacks/$MYPROG" \) ] ;then
    xhelp
    exit 1
fi

[ $PBARCH = arm ] && RARCH=arm || RARCH=x86_64

############################################
# Download new sources packages.
############################################
(
    cd packages
    [ ! -d openshot ] && mkdir openshot
    (
	cd openshot
	for i in openshot_qt lxml inkscape opencolorio pybind11 openimageio \
			     numpy3 tbb Blender libopenshot ;do
	    xgetsbosrc "$i"
	done
	xlocalsrcpac gstreamer0 "gstreamer-0.10.36.tar.xz"
	xlocalsrcpac gst-plugins-base0 "gst-plugins-base-0.10.36.tar.xz"
	xgetsrc python2-mlt "$PATHMLT"
	xgetsrc python2-libcaca "$PATHLIBCACA"
	xgetsrc python2-libwebp "$PATHLIBWEBP"
	xgetsrc openshot "$PATHOPENSHOT"
	# python-pillow6 : re-add python2.7 support for openshot.
	# Pillow 7 from current Slackware drop support of python2.
	rm -f python-pillow-[0-9]*.t?z*
	xgetsrc python-pillow6 "$PATHPYTHONPIL"
    )
    [ ! -d pitivi ] && mkdir pitivi
    (
	cd pitivi
	for i in blas lapack scipy3 gst-python3 python3-dateutil \
		      python3-cycler python3-kiwisolver python3-pyparsing \
		      python3-tornado pytz python3-matplotlib \
		      gstreamer-editing-services gsound libpeas pitivi ;do
	    xgetsbosrc "$i"
	done
    )
    xgetsbosrc gst-plugins-bad
    xgetsbosrc hplip-plugin
    xgetsrc openal-soft "$PATHOPENAL"
    xgetsrc libtxc_dxtn "$PATHLIBTXC_DXTN"
    xgetsrc libgaminggear "$PATHLIBGAMINGGEAR"
    rm -f acpibrightness-[0-9]*-x86_64-*.t?z*
    rm -f dawconfig-[0-9]*-*.tgz*
    xlocalsrcpac acpibrightness ""
    xgetsrc dawconfig "$PATHPAJACKCON"
)

############################################
(
    cd packages2
    xgetsbosrc roccat-tools
    xgetsbosrc PyYAML
    xgetsbosrc lutris
    xgetsbosrc lsdvd
    xlocalsrcpac kmplayer "kmplayer_0.11.5b.tar.bz2"
    xgetsrc denemo "$PATHDENEMO"
    # Guile 2.2 supprime en janvier. Utile a denemo.
    xgetsrc guile2.2 "$PATHGUILE22"
    # Discord just being put here. No packages done for now.
    xgetsbosrc discord $RARCH
    #xpurgepac discord tar.gz
    # Update Youtube LUA file for VLC.
    xgeturl "$PATHVLCYOUTUBE"
)

############################################
(
    cd packages3
    xgetsrc bsddb3 "$PATHBSDDB3"
    xgetsrc db53 "$PATHDB53"
    xgetsrc db53 "$PATHDB53BIS"
    xgetsbosrc pyicu
    xgetsrc gramps "$PATHGRAMPS"
    xgetsbosrc goocanvas2
    xgetsbosrc msgpack-python
)

############################################
(
    cd packages4
    xgetsrc xrdp "$PATHXRDP"
    xgetsrc xorgxrdp "$PATHXORGXRDP"
    xgetsrc SFML "$PATHSFML"
    xgetsrc vbam "$PATHVBAM"
    xgetsrc fbida "$PATHFBIDA"
    # The one of Slackware is too old for Opencv 4.4.0.
    xgetsrc eigen3 "$PATHEIGEN3"
    xgetsrc opencv "$PATHOPENCV"
    xgetsrc opencv "$PATHOPENCVBIS"
    for i in kaffeine gradle audiveris vokoscreen ;do
	xgetsbosrc "$i"
    done
    for i in opera signal-desktop zoom-linux vivaldi ;do
	xgetsbosrc "$i" $RARCH
    done
)
