#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019

MYPWD=`pwd`
export HOMESLACK="$MYPWD"
SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware'
SLACKMULTI="$SLACKMIR/people/alien/multilib/current"
SLACKKDEFW="$SLACKMIR/people/alien-kde/current/latest/x86_64/kde/frameworks"

# can be done non root.
wget -N -np -nH --cut-dirs=4 -r "$SLACKMIR/slackware64-current/"
find slackware64-current -name 'index.html*' -exec rm -f {} \;

xpurgepac () {
    pac="$1"
    suf="$2"
    LAST=`ls -1t ${pac}*.$suf|head -1`
    for j in ${pac}*.$suf ;do
	if [ "$j" != "$LAST" ] ;then
	    echo "Delete : $j"
	    rm -f "$j"
	fi
    done
}

# Nettoyage des doublons
cd slackware64-current
find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
    pack=`echo $i|sed 's@-[0-9].*$@@'`
    xpurgepac "$pack-[0-9]" txt
    xpurgepac "$pack-[0-9]" t?z
    xpurgepac "$pack-[0-9]" asc
done
cd ..
echo "Copie Slackware current faite."

# Multilib Alien Bob.
# can be done non root.
wget -N -np -nH --cut-dirs=7 -r "$SLACKMULTI/"
find current -name 'index.html*' -exec rm -f {} \;

# Nettoyage des doublons
cd current
find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
    pack=`echo $i|sed 's@-[0-9].*$@@'`
    xpurgepac "$pack-[0-9]" lst
    xpurgepac "$pack-[0-9]" meta
    xpurgepac "$pack-[0-9]" txt
    xpurgepac "$pack-[0-9]" t?z
    xpurgepac "$pack-[0-9]" asc
    xpurgepac "$pack-[0-9]" md5
done
cd ..

cd slackware64-current
ln -sf ../current .
ln -sf ../perso .
ln -sf ../pbslacks .
ln -sf ../bumblebee .
ln -sf ../divers .
ln -sf ../packages* .
cd ..

# Frameworks KDE5
cd packages4
wget -N -np -nH --cut-dirs=10 -r "$SLACKKDEFW/"
find frameworks -name 'index.html*' -exec rm -f {} \;

# Nettoyage des doublons
cd frameworks
find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
    pack=`echo $i|sed 's@-[0-9].*$@@'`
    xpurgepac "$pack-[0-9]" lst
    xpurgepac "$pack-[0-9]" meta
    xpurgepac "$pack-[0-9]" txt
    xpurgepac "$pack-[0-9]" t?z
    xpurgepac "$pack-[0-9]" asc
    xpurgepac "$pack-[0-9]" md5
done
cd ..
