#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# can be done non root.

MYPWD=$(pwd)
export HOMESLACK="$MYPWD"
SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware'
SLACKMULTI="$SLACKMIR/people/alien/multilib/current"
SLACKKDEFW="$SLACKMIR/people/alien-kde/current/latest/x86_64/kde/frameworks"
GPARTEDISO="https://downloads.sourceforge.net/gparted/gparted-live-1.0.0-5-amd64.iso"

# Function for getting packages.
myrget () {
    prof=$1
    gpath="$2"
    pack="$3"
    wget -N -nv -np -nH --cut-dirs=$prof -r "$gpath/"
    find "$pack" -name 'index.html*' -exec rm -f {} \;
}

# Function for purge old packages.
xpurgepac () {
    pac="$1"
    suf="$2"
    last=$(ls -1t ${pac}*.$suf|head -1)
    for j in ${pac}*.$suf ;do
	if [ "$j" != "$last" ] ;then
	    echo "Delete : $j"
	    rm -f "$j"
	fi
    done
}

myrget 4 "$SLACKMIR/slackware64-current" slackware64-current

# Nettoyage des doublons
if [ -d slackware64-current ] ;then
    cd slackware64-current
    find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
        pack=$(echo $i|sed 's@-[0-9].*$@@')
        xpurgepac "$pack-[0-9]" txt
        xpurgepac "$pack-[0-9]" t?z
        xpurgepac "$pack-[0-9]" asc
    done
    cd ..
    echo "Copie Slackware current faite."
fi

# Multilib Alien Bob.
# can be done non root.
myrget 7 "$SLACKMULTI" current

# Nettoyage des doublons
if [ -d current ] ;then
    cd current
    find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
        pack=$(echo $i|sed 's@-[0-9].*$@@')
        xpurgepac "$pack-[0-9]" lst
        xpurgepac "$pack-[0-9]" meta
        xpurgepac "$pack-[0-9]" txt
        xpurgepac "$pack-[0-9]" t?z
        xpurgepac "$pack-[0-9]" asc
        xpurgepac "$pack-[0-9]" md5
    done
    cd ..
fi

if [ -d slackware64-current ] ;then
    cd slackware64-current
    ln -sf ../current .
    ln -sf ../perso .
    ln -sf ../pbslacks .
    ln -sf ../bumblebee .
    ln -sf ../divers .
    ln -sf ../packages* .
    cd ..
fi

# Frameworks KDE5 Alien Bob
if [ -d packages4 ] ;then
    cd packages4
    myrget 10 "$SLACKKDEFW" frameworks

# Nettoyage des doublons
    if [ -d frameworks ] ;then
        cd frameworks
        find . -name '*.t?z'|grep -v '^./source/'|while read i;test "$i" != "" ;do
            pack=$(echo $i|sed 's@-[0-9].*$@@')
            xpurgepac "$pack-[0-9]" lst
            xpurgepac "$pack-[0-9]" meta
            xpurgepac "$pack-[0-9]" txt
            xpurgepac "$pack-[0-9]" t?z
            xpurgepac "$pack-[0-9]" asc
            xpurgepac "$pack-[0-9]" md5
        done
        cd ..
    fi
    cd ..
fi

# GParted
if [ ! -h Linuxiso ] ; then
    if [ ! -d ../Linuxiso ] ;then
	mkdir ../Linuxiso
    fi
    ln -s ../Linuxiso .
fi
cd Linuxiso
wget -N -nv --content-disposition "$GPARTEDISO"
cd ..
