#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
. "$XDIR/pbaspireinit"
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"
. "$XDIR/pbpathinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
}

if [ ! -d packages ] ;then
    xhelp
    exit 1
fi

############################################
# Download new versions of binary packages.
# Conrad and Slonly packages.
############################################
(
    cd packages
    for i in gimp-script-fu x265 skypeforlinux-bin ;do
	xgetpac "$i-" "$SLACKCF/$i" 3
    done
    for i in frei0r-plugins libvdpau-va-gl openshot ;do
	xgetpac "$i-" "$SLACKDJ" 5
    done
    (
	cd 32
	for i in wxPython ;do
	    xgetpac "$i-" "$SLACKDJ32" 5
	done
    )
)
xpurgeindex packages

############################################
(
    cd packages2
    for i in jq lua lua53 oniguruma valgrind ;do
	xgetpac "$i-" "$SLACKCF/$i" 3
    done
    for i in guile1.8 ;do
	xgetpac "$i-" "$SLACKDJ" 5
    done
)
xpurgeindex packages2

############################################
(
    cd packages4
    for i in exiftool unrar telegram-bin ;do
	xgetpac "$i-" "$SLACKCF/$i" 3
    done
    for i in xcftools ;do
	xgetpac "$i-" "$SLACKDJ" 5
    done
    [ ! -d tesseract4 ] && mkdir tesseract4
    (
	cd tesseract4
	for i in leptonica tesseract ;do
	    xgetpac "$i-" "$SLACKCF/$i" 3
	done
    )
)
cp pbslacks/tesseract4/* packages4/tesseract4
xpurgeindex packages4
