#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

XDIR="$(dirname $0)"
MYPWD=$(pwd)
PBARCH="$(basename "$MYPWD"|cut -d '-' -f2)"
if [ "$PBARCH" = x64 ] ;then
    . "$XDIR/pbaspireinit"
else
    . "$XDIR/pbaspirearminit"
fi
. "$XDIR/pbinclude"
. "$XDIR/pbaspireinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
    echo
    echo '> ../pbslacks/$MYPROG'
}

if [ ! -d packages -o \
       \( "$0" != "../pbslacks/$MYPROG" -a "$0" != "pbslacks/$MYPROG" \) ] ;then
    xhelp
    exit 1
fi

XLANG=$(echo $LANG|cut -d '.' -f1|cut -d '_' -f1)

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-lang" ] ;then
	shift
	XLANG="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

# Depends on $XLANG

[ ! -d packages/Mozilla ] && mkdir packages/Mozilla
(
    cd packages/Mozilla
    if [ "$PBARCH" = x64 ] ;then
	. "$XDIR/pbpathinc"
	xgeturl "$XFIREFOX"
	xpurgepac 'firefox-' tar.bz2

	xgeturl "$XTHUNDERBIRD"
	xpurgepac 'thunderbird-' tar.bz2
    elif  [ "$PBARCH" = arm ] ;then
	xgetsbosrc thunderbird
	xgetsbosrc libffi6
	xgetsbosrc libevent6
	xpurgepac 'thunderbird/thunderbird_' deb
    fi
)
