#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"
. "$(dirname $0)/pbaspireinc"

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
}

if [ ! -d packages ] ;then
    xhelp
    exit 1
fi

SLACKPONCE="http://ponce.cc/slackware/slackware64-current/packages"
SLACKPONCE32="http://ponce.cc/slackware/slackware-current/packages"

cd packages
for i in ladspa_sdk swfdec x264 libdvdcss vid.stab ;do
    xgetpac "$i-" "$SLACKPONCE" 3
done
cd 32
for i in libdvdcss ;do
    xgetpac "$i-" "$SLACKPONCE32" 3
done
cd ../..
xpurgeindex packages

cd packages2
for i in gtksourceview3 ;do
    xgetpac "$i-" "$SLACKPONCE" 3
done
cd ..
xpurgeindex packages2

cd packages3
for i in graphviz ;do
    xgetpac "$i-" "$SLACKPONCE" 3
done
cd ..
xpurgeindex packages3

cd packages4
for i in hdf5 numpy ;do
    xgetpac "$i-" "$SLACKPONCE" 3
done
if [ ! -d audacity ] ;then
    mkdir audacity
fi
cd audacity
for i in celt051 ;do
    xgetpac "$i-" "$SLACKPONCE" 3
done
cd ../..
xpurgeindex packages4
