#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xpurgetmp () {
    ppac="$1"
    rm -f /tmp/"${ppac}-"[0-9]*.t?z
    rm -f /tmp/"${ppac}-"master*.t?z
    rm -rf /tmp/"${ppac}-"[0-9]*
    rm -rf /tmp/"${ppac}-"master*
    rm -rf /tmp/*/"${ppac}-"[0-9]*
    rm -rf /tmp/*/"${ppac}-"master*
    rm -rf /tmp/package-"$ppac"
    rm -rf /tmp/*/package-"$ppac"
}

xcleanpac() {
    pac="$1"
    dest="$2"
    cp "/tmp/${pac}-"[0-9m]*.t?z* "$dest"
    chown ${MYUSER}.$MYGROUP "$dest/${pac}"-[0-9m]*.t?z*
    xpurgetmp "$pac"
    xpurgepac "$dest/$pac-[0-9]" t?z
    xpurgepac "$dest/$pac-master" t?z
}

xmakealienpac () {
    XDIR="$1"
    pac="$2"
    dest="$3"
    [ -z "$dest" ] && dest="$XDIR"
    if [ $RECOMP -eq 1 -a -d "${XDIR}/$pac" ] ;then
	rm -rf /tmp/build/package-* /tmp/build/tmp-*
	(
	    # patch
	    LLPATCH="$(pwd)/pbslacks/builds/alien/${pac}.patch"
	    cd "${XDIR}/$pac"
	    [ -f "$LLPATCH" ] && cat "$LLPATCH"|patch -f -p0
	    chown -R ${MYUSER}.$MYGROUP *
	    # build
	    sh "./${pac}.SlackBuild"
	    ERR=$?;chown -R ${MYUSER}.$MYGROUP *
	    if [ $ERR -ne 0 ] ;then
		mygt 'Correct this error and relaunch this script. Press a key to end.'
		read c;exit 1
	    fi
	)
	[ $? -ne 0 ] && exit 1
	xcleanpac "$pac" "$dest"
	chown -R ${MYUSER}.$MYGROUP "$dest/$pac"
	# Upgrade packages.
        upgradepkg --install-new --reinstall "$dest/${pac}"-[0-9m]*.t?z
    fi
}

xmakepac () {
    XDIR="$1"
    pac="$2"
    XSUB="$3"
    dest="$XDIR/$XSUB"
    if [ $RECOMP -eq 1 -a -d "${XDIR}/$pac" ] ;then
	(
	    cd "${XDIR}/$pac"
	    ./${pac}.SlackBuild
	    if [ $? -ne 0 ] ;then
		mygt 'Correct this error and relaunch this script. Press a key to end.'
		read c;exit 1
	    fi
	)
	[ $? -ne 0 ] && exit 1
	xcleanpac "$pac" "$dest"
    fi
    if [ "$XSUB" = '32' ] ;then
    	(
	    cd "$dest"
	    if [ $RECOMP -eq 1 ] ;then
		(unset TAG;unset ARCH
		 convertpkg-compat32 -i "$pac-"'*.t?z' -d ../compat32
		 chown ${MYUSER}.$MYGROUP ../compat32/${pac}-compat32-*.t?z
		)
	    fi
	    xpurgetmp ${pac}-compat32
	    upgradepkg --install-new --reinstall ../compat32/${pac}-compat32-*.t?z
	    rm -f /usr/lib/lib*.la
	)
	[ $? -ne 0 ] && exit 1
    elif [ "$XSUB" = '' ] ;then
	upgradepkg --install-new --reinstall "$XDIR/${pac}"-[0-9m]*.t?z
	rm -f $XLIBDIR/lib*.la
    fi
    exit 0
}
