#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"
. "$(dirname $0)/pbaspireinc"

if [ ! $UID = 0 ]; then
    mygt 'This script must be run as root.'
    exit 1
fi

xhelp () {
    mygt 'Launch this script in the directory including bumblebee.'
}

if [ ! -d bumblebee ] ;then
    xhelp
    exit 1
fi

MYUSER=produits
MYGROUP=users

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-u" ] ;then
	shift
	MYUSER="$1"
    elif [ "$MYARG" = "-g" ] ;then
	shift
	MYGROUP="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

MYPWD=$(pwd)
HOMESLACK="$MYPWD"
HOMEBUMBLE=~/Bumblebee-SlackBuilds

mygt 'Redo the Bumblebee Slackware packages.\nIf already done on an upgraded host use the packages already generated with upgradebumblebee.'|sed 's@\\n@\n@g'

export UPDATE=no
rm -rf $HOMEBUMBLE

if [ -f "$HOMESLACK/bumblebee/Crazybee/Bumblebee-SlackBuilds.tgz" ] ;then
    cd 
    tar xvfz "$HOMESLACK/bumblebee/Crazybee/Bumblebee-SlackBuilds.tgz"
    export UPDATE=no
    cd Bumblebee-SlackBuilds
    sh ./crazybee.sh
else
    sh "$HOMESLACK/bumblebee/Crazybee/crazybee.sh"
fi

cd "$HOMESLACK/bumblebee"
cp $HOMEBUMBLE/nouveau-blacklist/xf86-video-nouveau-blacklist-noarch-1.t?z .

for i in libbsd primus primus_vk bbswitch nvidia-bumblebee bumblebee \
nvidia-kernel ;do
    cp "/tmp/${i}-"*.t?z .
    rm -f "/tmp/${i}-"*.t?z
    xpurgepac "${i}-" t?z
done
chown ${MYUSER}.$MYGROUP *.t?z
rm -rf /tmp/bbsb

# Not sufficient. Should rmmod nouveau driver.
[ -x /etc/rc.d/rc.bumblebee ] && /etc/rc.d/rc.bumbleebee restart
