#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# Recompilations a faire apres reboot.

. "$(dirname $0)/pbinclude"
. "$(dirname $0)/pbupgradeinc"
. "$(dirname $0)/pbcompileinc"

if [ ! $UID = 0 ]; then
    mygt 'This script must be done as root. Exit.'
    exit 1
fi

xhelp () {
    mygt 'Launch this script in the directory including packages, packages2 et al.'
    echo
    echo '> pbslacks/$MYPROG'
}

if [ ! -d kde5 -o '(' ! -h pbslacks -a ! -d pbslacks ')' ] ;then
    xhelp
    exit 1
fi

MYUSER=produits
MYGROUP=users
RECOMP=1
ISALL=1
ISKDE5=0

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-u" ] ;then
	shift
	MYUSER="$1"
    elif [ "$MYARG" = "-g" ] ;then
	shift
	MYGROUP="$1"
    elif [ "$MYARG" = "-norecomp" ] ;then
        RECOMP=0
    elif [ "$MYARG" = "-iskde5" ] ;then
	ISKDE5=1;ISALL=0
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

if [ $ISALL -eq 1 ] ;then
    ISKDE5=1
fi

mygt 'Only after a system update and reboot.\nIf already done on this or another machine, this script is not useful.\nPress a touch for continue or abort.'|sed 's@\\n@\n@g'
read c

# ===========================================================
# Some helper functions.

# ===========================================================
rm -f $XLIBDIR/lib*.la
XNPROC=$(nproc)
export CMAKE_BUILD_PARALLEL_LEVEL=$XNPROC
export MAKEFLAGS="-j$XNPROC"
export PKGTYPE=txz
export TAG=_PB
# ===========================================================

if [ $ISKDE5 -eq 1 ] ;then
    (
	export BUILD=1PB;export EXIT_ON_FAIL=yes
	(
	    # Sources are gotten from the Web by pbaspirecore called par pbsetup.
	    cd kde5/source
	    # Next we create and install the packages.
	    sh kde.SlackBuild applications:ktuberling
	)
	(
	    cd kde5
	    [ ! -d applications ] && mkdir applications
	    # We keep the packages in kde5 so that other computer can be
	    # installed directly.
	    cd applications
	    [ -d /tmp/kde_build/applications ] && \
		cp /tmp/kde_build/applications/*.t?z .
	    cp /tmp/kde_build/*.t?z .
	    chown ${MYUSER}:$MYGROUP *.t?z
	    xpurgesrc 't?z'
	    rm -rf /tmp/kde_build
	)
	xhookframew
    )
fi
