#! /bin/sh

if [ ! $UID = 0 ]; then
  cat << EOF
This script must be run as root.
EOF
  exit 1
fi

if [ ! -d bumblebee ] ;then
    echo "Script a lancer dans le repertoire contenant bumblebee."
    exit 1
fi

MYPWD=`pwd`
HOMESLACK="$MYPWD"

echo "Recreation des packages Slackware de Bummblebee."
echo "Si deja fait sur une machine a jour, ne pas refaire et"
echo "  utilisez les paquets generes dans bumblebee (avec pbupgradebumblebee)."
echo "A installer avec pbupgradenumblebee."

export UPDATE=no
rm -rf ~/Bumblebee-SlackBuilds

cd
tar xvf $HOMESLACK/bumblebee/Crazybee/Bumblebee-SlackBuilds.tar
export UPDATE=no
cd Bumblebee-SlackBuilds
sh ./crazybee.sh

for i in libbsd primus bbswitch nvidia-bumblebee bumblebee nvidia-kernel ;do
    cp /tmp/${i}-* $HOMESLACK/bumblebee
done
