#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

ISGETTEXT=1
[ x$(which gettext.sh 2> /dev/null) = 'x' ] && ISGETTEXT=0

if [ $ISGETTEXT -eq 1 ] ;then
    MYPWD=$(pwd)
    export TEXTDOMAIN=pbslacks
    if [ "$PBSDIR" != '' ] ;then
	export TEXTDOMAINDIR="$PBSDIR/locale"
    else
	export TEXTDOMAINDIR="$(cd $(dirname $0); pwd)/locale";cd "$MYPWD"
    fi
    . gettext.sh
    mygt () {
	gettext "$1";echo
    }
    emygt () {
	eval_gettext "$1";echo
    }
else
    mygt () {
	echo "$1"
    }
    emygt () {
	STR=$(echo "$1"|sed 's@\\n@\\\\n@')
	eval echo $STR
    }
fi

XTEST=0
ISDIAL=1
[ x$(which dialog 2> /dev/null) = 'x' ] && ISDIAL=0

nodialog () {
    echo '------------------------------------'
    echo "  $1"
    echo '------------------------------------'
    if [ "$3" != '' ] ; then
	cat "$2"|sed 's@\\n@\n@g'
    else
	cat "$2"
    fi
}

MYPROG=$(basename "$0")
PBMYPROG="pbslacks/$MYPROG"
MYPWD=$(pwd)
PBDIRPROG="$(cd $(dirname $0); pwd)";cd "$MYPWD"
PBARCH=x64
if [ ! -d slackware64-current ] ;then
    if [ -d slackwarearm-current ] ;then
	PBARCH=arm
    else
	TARCH="$(basename "$(pwd)"|cut -d '-' -f1|cut -c9-)"
	[ "$TARCH" = 'arm' ] && PBARCH=arm	
    fi
fi  
[ "$PBARCH" = x64 ] && XLIBDIR=/usr/lib64 || XLIBDIR=/usr/lib

# Function last prefix file.
xlast () {
    pac="$1"
    ls -1dt ${pac}* 2> /dev/null|head -1
}

# Function for purge old packages.
xpurgepac () {
    ppac="$1"
    suf="$2"
    last=$(ls -1t ${ppac}*.$suf 2> /dev/null|head -1)
    for j in $(ls ${ppac}*.$suf 2> /dev/null) ;do
	if [ "$j" != "$last" ] ;then
	    emygt "Delete : \$j"
	    rm -f "$j"
	fi
    done
}

xpurgesrc () {
    SUFPACK="$1"
    shift
    SUFS="$@"
    find . -name '*'$SUFPACK | while read i;test "$i" != "" ;do
	pack=$(echo $i|sed 's@-[0-9].*$@@')
	xpurgepac "$pack-[0-9]" $SUFPACK
	for j in $SUFS ; do
	    xpurgepac "$pack-[0-9]" ${SUFPACK}.$j
	done
    done
}
