#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xhelp () {
    echo "> ./pblocale [-h|-help] [-init new_language] [progname]"
}

XINIT=
XPROG=

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-init" ] ;then
	shift
	XINIT="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    elif [ "$MYARG" = "all" ] ;then
	XPROG="pbaspire pbaspirealien pbaspirecore pbaspireinc pbaspireinit pbaspiremoz pbaspireother pbaspireponce pbaspireslonly pbaspiresources pbcompilebumblebee pbcompilepost pbinclude pblocale pbmakeusb pbmount pbsetup pbstophib pbunmount pbupgrade pbupgradebumblebee pbupgrademoz pbmakeiso pbmakeiso2usb"
    else
	XPROG="$XPROG $MYARG"	
    fi
    shift
done

MYPWD=$(pwd)
TEXTDOMAIN=pbslacks
TEXTDOMAINDIR="$(cd $(dirname $0); pwd)/locale";cd "$MYPWD"

for i in $XPROG ; do
    xgettext -d "$TEXTDOMAIN" -p "$TEXTDOMAINDIR" -L Shell \
	--copyright-holder='Pierre Brochard' \
	--msgid-bugs-address=pierre.brochard.1982@m4x.org -kmygt -kemygt \
	-j --omit-header $i
done

if [ "$XINIT" != '' ] ;then
    mkdir "$TEXTDOMAINDIR/$XINIT"
    msginit -i "$TEXTDOMAINDIR/pbslacks.po" -l "$XINIT" \
	-o "$TEXTDOMAINDIR/$XINIT/pbslacks.po"
fi

ls "$TEXTDOMAINDIR"|while read i;test "$i" != "" ;do
    l="$TEXTDOMAINDIR/$i"
    if [ -d "$l" ] ;then
	msgmerge "$l/pbslacks.po" "$TEXTDOMAINDIR/pbslacks.po" \
	    -o "$l/pbslacks.po"
	msgfmt -o "$l/LC_MESSAGES/pbslacks.mo" "$l/pbslacks.po"
    fi
done
