#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# Use at your own risk. The autodetected partition is the last VFAT one.
# Be sure it is not your hard drive.

# If you are in the plugdev group, you can execute this script as a normal user.

# You may prefer the pbmakeusb script for the same task.
# This script produce an USB stick not writable and not extensible
# but good enough to install a Slackware distribution on your computer.

# Plug an USB stick
# And lauch this script without plug another one in the meantime.
# This script will :
#   -guess the device name of the USB stick.
#   -copy the iso file givent in argument.

. "$(dirname $0)/pbinclude"

if [ "$1" = '' ] ;then
    mygt "Give the name of the iso file to copy on the USB stick."
    exit 1
fi

NAMEISO="$1"

if [ ! -f "$NAMEISO" ] ;then
    mygt "Give the name of an existant iso file to copy on the USB stick."
    exit 1
fi

mygt "Put your USB stick on an USB port and press Enter."
read c
sleep 3
MYDEVNAME=$(/sbin/fdisk -l 2> /dev/null| tail -12 | grep ' /dev/[a-z]'|\
	sed 's@^.*\(/dev/[a-z]*\).*$@\1@')
MYRDEV=$(echo $MYDEVNAME|cut -c 6-)
MYTEST=$(dmesg|tail -10|grep $MYRDEV 2> /dev/null|wc -l)
[ $MYTEST -lt 1 ] && MYDEVNAME=

/sbin/fdisk -l 2> /dev/null
emygt "Your device name is \$MYDEVNAME. Is this correct ? y(es) or n(o) :"
read c

if [ "$c" = 'y' -a "$MYDEVNAME" != '' ] ;then
    dd if=$NAMEISO of=$MYDEVNAME bs=1M
    sync
fi
