#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019

# Use at your own risk. The autodetected partition is the last VFAT one.
# Be sure it is not your hard drive.
# If you are in the plugdev group, you can execute thos script as a normal user.

# Plug an USB stick
# And lauch this script without plug another one in the meantime.
# This script will :
#   -guess the device name of the USB stick.
#   -copy the iso file givent in argument.

if [ "$1" = '' ] ;then
    echo "Give the name of the iso file to copy on the USB stick."
    exit 1
fi

NAMEISO="$1"

if [ ! -f "$NAMEISO" ] ;then
    echo "Give the name of an existant iso file to copy on the USB stick."
    exit 1
fi

echo "Put your USB stick on an USB port and press Enter."
read c
sleep 3
MYDEVNAME=`/sbin/fdisk -l 2> /dev/null| tail -1 | grep 'FAT32$'|cut -d ' ' -f1|cut -d '1' -f1`

if [ "$MYDEVNAME" = '' ] ;then
# If it is an already created Slackware USB stick."
    MYDEVNAME=`/sbin/fdisk -l 2> /dev/null| tail -2 | grep 'EFI '|cut -d ' ' -f1|cut -d '2' -f1`
fi

/sbin/fdisk -l 2> /dev/null
echo "Your device name is $MYDEVNAME. Is this correct ? y(es) or n(o) :"
read c

if [ "$c" = 'y' -a "$MYDEVNAME" != '' ] ;then
    dd if=$NAMEISO of=$MYDEVNAME bs=1M
    sync
fi
