#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019

if [ ! -d slackware64-current ] ;then
    echo "Script a lancer dans le repertoire contenant slackware64-current fraichement aspire."
    echo "Launch this script in the directory including slackware64-current."
    exit 1
fi

MYPWD=`pwd`
NAMEISO=`basename "$MYPWD"`.iso

echo "The ISO image will be created with $NAMEISO name."

cd slackware64-current

# Copied from isolinux/README.TXT in the slackware64-current repository.

xorriso -as mkisofs \
  -iso-level 3 \
  -full-iso9660-filenames \
  -R -J -A "Slackware Install" \
  -hide-rr-moved \
  -v -d -N \
  -eltorito-boot isolinux/isolinux.bin \
  -eltorito-catalog isolinux/boot.cat \
  -no-emul-boot -boot-load-size 4 -boot-info-table \
  -isohybrid-mbr /usr/share/syslinux/isohdpfx.bin \
  -eltorito-alt-boot \
  -e isolinux/efiboot.img \
  -no-emul-boot -isohybrid-gpt-basdat \
  -m 'source' \
  -volid "SlackDVD" \
  -output "../../$NAMEISO" \
  . ../current ../packages* ../bumblebee ../../divers ../../pbslacks ../../perso

cd ../..

echo "The iso created can be put on a DVD with (if not too big for your recorder) :"
echo "> growisofs -speed=2 -dvd-compat -Z /dev/dvd `pwd`/$NAMEISO"

echo "Or on an USB stick (sdX below is the name of the USB device) :"
echo "> dd if=`pwd`/$NAMEISO of=/dev/sdX bs=1M ;sync"
echo "Or launch :"
echo "> pbmakeiso2usb `pwd`/$NAMEISO"
