#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

xhelp () {
    mygt 'Launch this script in the directory including slackware64-current.'
    echo
    echo '> ../pbslacks/$MYPROG'
}

if [ ! -d slackware64-current -o \
       \( "$0" != "../pbslacks/$MYPROG" -a "$0" != "pbslacks/$MYPROG" \) ] ;then
    xhelp
    exit 1
fi

REPISO=../Linuxiso
if [ ! -d "$REPISO" ] ;then
    mkdir "$REPISO"
fi

MYPWD=$(pwd)
NAMEISO=$REPISO/$(basename "$MYPWD").iso
FNAMEISO=$MYPWD/$NAMEISO

echo '-------------------------------------------------'
emygt "The ISO image will be created with \$NAMEISO name."
echo '-------------------------------------------------'
echo '-------------------------------------------------'
emygt "If not too big for your recorder which should use double layer media,\nthe iso created can be put on a DVD with :\n> growisofs -speed=2 -dvd-compat -Z /dev/dvd \$FNAMEISO\n\n  Or your favorite DVD recorder.\n\n  Or on an USB stick (sdX below is the name of the USB device) :\n> dd if=\$FNAMEISO of=/dev/sdX bs=1M ;sync\n\n  Or launch :\n> pbmakeiso2usb \$FNAMEISO\n\n  Or lauch :\n> pbmakeusb"|sed 's@\\n@\n@g'
echo '-------------------------------------------------'

cd slackware64-current
XTEMPLIST=$(mktemp -p /tmp -t pbmakeisolist.XXXXXX)
find -L . -type d | grep "\./packages" | egrep -v 'package[^/]*($|/(ardour|audacity|compat32|openshot|pitivi|Mozilla|Httpfs|frameworks|audiveris|tesseract4|Steam)$)'|sed 's/^\./../g' > $XTEMPLIST
find -L . -type d | grep "\./kde5" | egrep -v 'kde5($|/(frameworks|deps|plasma-extra)$)'|sed 's/^\./../g' >> $XTEMPLIST
find -L . -type d | grep "\./kde4" | egrep -v 'kde4($|/(kde|deps)$)'|sed 's/^\./../g' >> $XTEMPLIST

# Copied then adapted from isolinux/README.TXT in the
# slackware64-current repository.

set -e
xorriso -as mkisofs -iso-level 3 \
    -full-iso9660-filenames -R -J -A "Slackware Install" \
    -hide-rr-moved -v -d -N -eltorito-boot isolinux/isolinux.bin \
    -eltorito-catalog isolinux/boot.cat \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -isohybrid-mbr /usr/share/syslinux/isohdpfx.bin \
    -eltorito-alt-boot -e isolinux/efiboot.img \
    -no-emul-boot -isohybrid-gpt-basdat -m source \
    -m Bumblebee-SlackBuilds.tgz -exclude-list $XTEMPLIST \
    -volid "SlackDVD" -output "../$NAMEISO" -graft-points . \
    bumblebee/Crazybee/Bumblebee-SlackBuilds.tgz=../../Crazybee/Bumblebee-SlackBuilds.tgz \
    bumblebee/=../bumblebee current/=../current packages/=../packages \
    packages2/=../packages2 packages3/=../packages3 packages4/=../packages4 \
    kde5/=../kde5 kde4/=../kde4 divers/=../../divers pbslacks/=../../pbslacks \
    perso/=../../perso gpgkeys/=../gpgkeys
rm -f $XTEMPLIST
cd ..
