#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

xhelp () {
    mygt 'Launch this script in the directory including slackware64-current.'
    echo
    echo '> pbslacks/pbmakeiso'
}

if [ ! -d slackware64-current ] ;then
    xhelp
    exit 1
fi

REPISO=../Linuxiso
if [ ! -d "$REPISO" ] ;then
    mkdir "$REPISO"
fi

MYPWD=$(pwd)
NAMEISO=$REPISO/$(basename "$MYPWD").iso
FNAMEISO=$MYPWD/$NAMEISO

echo '-------------------------------------------------'
emygt "The ISO image will be created with \$NAMEISO name."
echo '-------------------------------------------------'

cd slackware64-current

# Copied from isolinux/README.TXT in the slackware64-current repository.

set -e
xorriso -as mkisofs \
    -iso-level 3 \
    -full-iso9660-filenames \
    -R -J -A "Slackware Install" \
    -hide-rr-moved \
    -v -d -N \
    -eltorito-boot isolinux/isolinux.bin \
    -eltorito-catalog isolinux/boot.cat \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -isohybrid-mbr /usr/share/syslinux/isohdpfx.bin \
    -eltorito-alt-boot \
    -e isolinux/efiboot.img \
    -no-emul-boot -isohybrid-gpt-basdat \
    -m 'source' \
    -volid "SlackDVD" \
    -output "../$NAMEISO" \
    -graft-points \
    . current/=../current packages/=../packages packages2/=../packages2 \
    packages3/=../packages3 packages4/=../packages4 bumblebee/=../bumblebee \
    divers/=../../divers pbslacks/=../../pbslacks perso/=../../perso \
    gpgkeys/=../gpgkeys
cd ..

echo '-------------------------------------------------'
emygt "If not too big for your recorder which should use double layer media,\nthe iso created can be put on a DVD with :\n> growisofs -speed=2 -dvd-compat -Z /dev/dvd \$FNAMEISO\n\n  Or your favorite DVD recorder.\n\n  Or on an USB stick (sdX below is the name of the USB device) :\n> dd if=\$FNAMEISO of=/dev/sdX bs=1M ;sync\n\n  Or launch :\n> pbmakeiso2usb \$FNAMEISO\n\n  Or lauch :\n> pbmakeusb"|sed 's@\\n@\n@g'
echo '-------------------------------------------------'
