#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

FN="$0";[ "$0" = "$(basename $0)" ] && FN=$(which "$0")
PBSDIR=$(dirname "$(readlink -f "$FN")")
. "$PBSDIR/pbinclude"

xhelp () {
    mygt "Give the name of the iso file or the device to mount."
    echo
    echo "> $(basename $0) nameiso|/dev/xxx"
}

NAMEISO="$1"

if [ "$1" = '' -o '(' ! -b "$NAMEISO" -a ! -f "$NAMEISO" ')' ] ;then
    xhelp
    exit 1
fi

xlosetup () {
    XL="$1"
    udisksctl loop-setup -f "$XL"|sed 's@^.* \(.*\)\.$@\1@'
}

xmount () {
    XL="$1"
    udisksctl mount -b "$XL"|cut -d ' ' -f4-|sed 's@^\(.*\)\.$@\1@'
}

if [ -b "$NAMEISO" ] ;then
    MNTDIR=$(xmount "$NAMEISO")
    XLOOP="$NAMEISO"
else
    XLOOP=$(xlosetup "$NAMEISO")
    sync
    emygt "Loop device is : \$XLOOP"

    if [ -b "${XLOOP}p1" ] ;then
        MNTDIR=$(xmount "${XLOOP}p1")
    else
        MNTDIR=$(xmount "${XLOOP}")
    fi
fi

if [ "$MNTDIR" != '' ] ;then
    emygt "Look at \$MNTDIR"
    mygt "unmount with :"
    echo "> pbunmountiso $XLOOP"
fi
