#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# List of sources packages.

PATHPYTHONPIL="https://github.com/python-pillow/Pillow/archive/6.2.2.tar.gz"
PATHGUILE22="https://ftp.gnu.org/gnu/guile/guile-2.2.6.tar.xz"
PATHDENEMO="http://git.savannah.gnu.org/cgit/denemo.git/snapshot/denemo-master.tar.gz"
PATHGOOCANVAS2='https://slackbuilds.org/slackbuilds/14.2/graphics/goocanvas2.tar.gz'
PATHGRAMPS="https://github.com/gramps-project/gramps/archive/v5.1.3.tar.gz"
PATHOPENAL="https://www.openal-soft.org/openal-releases/openal-soft-1.20.1.tar.bz2"
PATHLIBTXC_DXTN="https://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.bz2"
PATHLIBGAMINGGEAR="https://downloads.sourceforge.net/libgaminggear/libgaminggear-0.15.1.tar.bz2"
PATHKMPLAYER="https://anongit.kde.org/kmplayer.git"
PATHBSDDB3="https://files.pythonhosted.org/packages/e9/fc/ebfbd4de236b493f9ece156f816c21df0ae87ccc22604c5f9b664efef1b9/bsddb3-6.2.6.tar.gz"
PATHDB53="http://deb.debian.org/debian/pool/main/d/db5.3/db5.3_5.3.28+dfsg1.orig.tar.xz"
PATHDB53BIS="http://deb.debian.org/debian/pool/main/d/db5.3/db5.3_5.3.28+dfsg1-0.6.debian.tar.xz"
PATHPYICU="https://files.pythonhosted.org/packages/77/a2/7c22b63c3cab7e41cbf4a930b033f5fc3e47bc5b6b673020f5ba58cecdf2/PyICU-2.4.1.tar.gz"
PATHXRDP="https://github.com/neutrinolabs/xrdp/releases/download/v0.9.12/xrdp-0.9.12.tar.gz"
PATHXORGXRDP="https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.2.12/xorgxrdp-0.2.12.tar.gz"
PATHSFML="https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip"
PATHWXGTK3="https://github.com/wxWidgets/wxWidgets/archive/v3.0.4/wxWidgets-3.0.4.tar.gz"
PATHVBAM="https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.1.4/visualboyadvance-m-2.1.4.tar.gz"
PATHFBIDA="https://www.kraxel.org/releases/fbida/fbida-2.14.tar.gz"
PATHOPENCV="https://github.com/opencv/opencv/archive/4.4.0/opencv-4.4.0.tar.gz"
PATHOPENCVBIS="https://github.com/opencv/opencv_contrib/archive/4.4.0/opencv_contrib-4.4.0.tar.gz"
PATHDISCORD="https://discordapp.com/api/download?platform=linux&format=tar.gz"
PATHVLCYOUTUBE="https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua"
PATHMLT="https://github.com/mltframework/mlt/archive/v6.20.0.tar.gz"
PATHLIBCACA="http://caca.zoy.org/files/libcaca/libcaca-0.99.beta19.tar.gz"
PATHLIBWEBP="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz"
PATHEIGEN3='https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2'

# Path which are in package.info file inside the package.
# TODO : Should be updated from those PATH or the SlackBuilds from SBo updated.

PATHSBO='https://slackbuilds.org/slackbuilds/14.2'

PATHROCCATTOOLS="http://downloads.sourceforge.net/roccat/roccat-tools-5.9.0.tar.bz2"
PATHKAFFEINE="https://github.com/KDE/kaffeine/archive/master.zip"
PATHGRADLE="https://services.gradle.org/distributions/gradle-6.2.2-all.zip"
PATHAUDIVERIS="https://github.com/Audiveris/audiveris/archive/master.zip"
PATHSIGNALDESKTOP="https://sourceforge.net/projects/slackbuildsdirectlinks/files/signal-desktop/signal-desktop_1.36.1_amd64.deb"
PATHVOKOSCREEN="https://github.com/vkohaupt/vokoscreenNG/archive/3.0.3.tar.gz"
PATHZOOM="https://zoom.us/client/latest/zoom_x86_64.tar.xz"
# A renommer en openshot_qt pour eviter les conflits avec openshot 1.4
# "multimedia/openshot.tar.gz"
PATHOPENSHOT2="https://github.com/OpenShot/openshot-qt/archive/v2.5.1/openshot-qt-2.5.1.tar.gz"
# python3-certify : compile only. No modifs.
# "python/python3-certifi.tar.gz"
PATHPYTHON3CERTIFY="https://pypi.python.org/packages/source/c/certifi/certifi-2019.6.16.tar.gz"
# "graphics/inkscape.tar.gz'
PATHINKSCAPE='https://inkscape.org/gallery/item/13330/inkscape-0.92.4.tar.bz2'
# "graphics/Blender.tar.gz'
PATHBLENDER='https://download.blender.org/source/blender-2.82a.tar.xz'
# "graphics/openimageio.tar.gz'
PATHOPENIMAGEIO='https://github.com/OpenImageIO/oiio/archive/Release-2.0.13/oiio-Release-2.0.13.tar.gz'
# "graphics/opencolorio.tar.gz'
PATHOPENCOLORIO='https://github.com/imageworks/OpenColorIO/archive/v1.1.1/OpenColorIO-1.1.1.tar.gz'
# "python/pybind11.tar.gz'
PATHPYBIND11='https://github.com/pybind/pybind11/archive/v2.5.0/pybind11-2.5.0.tar.gz'
# "development/numpy3.tar.gz'
PATHNUMPY3='https://github.com/numpy/numpy/releases/download/v1.14.3/numpy-1.14.3.tar.gz'
# "libraries/tbb.tar.gz'
PATHTBB='https://github.com/oneapi-src/oneTBB/archive/2020_U2/tbb-2020_U2.tar.gz'
# "python/lxml.tar.gz'
PATHLXML='https://pypi.io/packages/source/l/lxml/lxml-4.4.1.tar.gz'
PATHOPERA='https://get.geo.opera.com/pub/opera-beta/70.0.3728.8/linux/opera-beta_70.0.3728.8_amd64.deb'

# List of aspire links.
# explicit mirror chosen here.
SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware'

SLACKKEYS='https://mirrors.slackware.com/slackware'
SLACKMULTI="$SLACKMIR/people/alien/multilib/current"
SLACKKDEFW="$SLACKMIR/people/alien-kde/current/latest/x86_64/kde/frameworks"

# GParted Live iso and VirtualBox for Windows.

GPARTEDISO="https://downloads.sourceforge.net/gparted/gparted-live-1.1.0-1-amd64.iso"
VBOXREP='https://download.virtualbox.org/virtualbox/6.1.14/'
VBOXARCH="$VBOXREP/VirtualBox-6.1.14-140239-Win.exe"
VBOXEXT="$VBOXREP/Oracle_VM_VirtualBox_Extension_Pack-6.1.14.vbox-extpack"
VBOXDOC="$VBOXREP/UserManual.pdf"

# Alien Bob list of repositories.

SLACKALIEN="$SLACKMIR/people/alien/slackbuilds"
SLACKALIEN2="$SLACKMIR/people/alien-kde/current/latest/x86_64/deps"
SLACKALIEN3="$SLACKMIR/people/alien/sbrepos/current/x86_64"
SLACKALIENSRC2="$SLACKMIR/people/alien-kde/source/latest/deps"

# Links for localized Mozilla Firefox and Thunderbird.

XFIREFOX="https://download.mozilla.org/?product=firefox-esr-next-latest-ssl&os=linux64&lang=$XLANG"
XTHUNDERBIRD="https://download.mozilla.org/?product=thunderbird-latest-SSL&os=linux64&lang=$XLANG"

# Links for binary packages from Conraid and Slackel.

SLACKCF="http://slack.conraid.net/repository/slackware64-current"
SLACKDJ="http://www.slackel.gr/repo/x86_64/current/slackel/extra"
SLACKDJ32="http://www.slackel.gr/repo/i486/current/slackel/extra"
SLACKDJPAR="http://www.slackel.gr/repo/x86_64/current"
SLACKDJPAR32="http://www.slackel.gr/repo/i486/current"

# Links for binary packages from Ponce.

SLACKPONCE="http://ponce.cc/slackware/slackware64-current/packages"
SLACKPONCE32="http://ponce.cc/slackware/slackware-current/packages"

# Links for binary packages from Slonly.

SLACKSLONLY="https://slackonly.com/pub/packages/current-x86_64"
SLACKSLONLY32="https://slackonly.com/pub/packages/current-x86"
SLACKSLONLY142="https://slackonly.com/pub/packages/14.2-x86_64"
