#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# List of aspire links.
# explicit mirror chosen here.
SLACKDIR='/pub/linux/distributions/slackware'
SLACKMIR="http://nephtys.lip6.fr$SLACKDIR"

[ "$SLACKVER" = '' ] && SLACKVER=15.0

SLACKKEYS='https://mirrors.slackware.com/slackware'
SLACKMULTI="$SLACKMIR/people/alien/multilib/${SLACKVER}"
SLACKMULTI_SRC="$SLACKMIR/people/alien/multilib/source/${SLACKVER}"

# GParted Live iso and VirtualBox for Windows.

GPARTEDISO="https://downloads.sourceforge.net/gparted/gparted-live-1.1.0-6-amd64.iso"
VBOXREP='https://download.virtualbox.org/virtualbox/6.1.18/'
VBOXARCH="$VBOXREP/VirtualBox-6.1.18-142142-Win.exe"
VBOXEXT="$VBOXREP/Oracle_VM_VirtualBox_Extension_Pack-6.1.18.vbox-extpack"
VBOXDOC="$VBOXREP/UserManual.pdf"

# Alien Bob list of repositories.

SLACKALIEN="$SLACKMIR/people/alien/slackbuilds"
SLACKALIEN2="$SLACKMIR/people/alien-kde/${SLACKVER}/latest/x86_64/deps"
SLACKALIEN3="$SLACKMIR/people/alien/sbrepos/${SLACKVER}/x86_64"
SLACKALIENSRC2="$SLACKMIR/people/alien-kde/source/latest/deps"

# Links for localized Mozilla Firefox and Thunderbird.

XFIREFOX="https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang=$XLANG"
XTHUNDERBIRD="https://download.mozilla.org/?product=thunderbird-latest-SSL&os=linux64&lang=$XLANG"
XFIREFOXXPI='https://ftp.mozilla.org/pub/firefox/releases/78.10.1esr/linux-x86_64/xpi/fr.xpi'

# Links for binary packages from Conraid and Slackel.

SLACKCF="http://slack.conraid.net/repository/slackware64-${SLACKVER}"
SLACKDJ="http://www.slackel.gr/repo/x86_64/${SLACKVER}/slackel/extra"
SLACKDJ32="http://www.slackel.gr/repo/i486/${SLACKVER}/slackel/extra"
SLACKDJPAR="http://www.slackel.gr/repo/x86_64/${SLACKVER}"
SLACKDJPAR32="http://www.slackel.gr/repo/i486/${SLACKVER}"

# Links for Gnome from SAXA.
SLACKDL="http://www.droplinegnome.org/files/3.36/x86_64/testing"

# Links for binary packages from Ponce.

SLACKPONCE="http://ponce.cc/slackware/slackware64-${SLACKVER}/packages"
SLACKPONCE32="http://ponce.cc/slackware/slackware-${SLACKVER}/packages"

# Links for binary packages from Slonly.

SLACKSLONLY="https://slackonly.com/pub/packages/${SLACKVER}-x86_64"
SLACKSLONLY32="https://slackonly.com/pub/packages/${SLACKVER}-x86"
SLACKSLONLY142="https://slackonly.com/pub/packages/14.2-x86_64"

# List of sources packages.

PATHPYTHONPIL="https://github.com/python-pillow/Pillow/archive/6.2.2.tar.gz"
PATHGUILE22="https://ftp.gnu.org/gnu/guile/guile-2.2.6.tar.xz"
PATHDENEMO="http://git.savannah.gnu.org/cgit/denemo.git/snapshot/denemo-master.tar.gz"
PATHGOOCANVAS2='https://slackbuilds.org/slackbuilds/14.2/graphics/goocanvas2.tar.gz'
PATHGRAMPS="https://github.com/gramps-project/gramps/archive/v5.1.3.tar.gz"
PATHOPENAL="https://www.openal-soft.org/openal-releases/openal-soft-1.21.0.tar.bz2"
PATHLIBTXC_DXTN="https://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.bz2"
PATHLIBGAMINGGEAR="https://downloads.sourceforge.net/libgaminggear/libgaminggear-0.15.1.tar.bz2"
PATHKMPLAYER="https://anongit.kde.org/kmplayer.git"
PATHBSDDB3="https://files.pythonhosted.org/packages/e9/fc/ebfbd4de236b493f9ece156f816c21df0ae87ccc22604c5f9b664efef1b9/bsddb3-6.2.6.tar.gz"
PATHDB53="http://deb.debian.org/debian/pool/main/d/db5.3/db5.3_5.3.28+dfsg1.orig.tar.xz"
PATHDB53BIS="http://deb.debian.org/debian/pool/main/d/db5.3/db5.3_5.3.28+dfsg1-0.8.debian.tar.xz"
PATHPYICU="https://files.pythonhosted.org/packages/31/46/fa08c8efae2951e67681ec24319f789fc1a74e2096dd74373e34c79319de/PyICU-2.6.tar.gz"
PATHXRDP="https://github.com/neutrinolabs/xrdp/releases/download/v0.9.12/xrdp-0.9.12.tar.gz"
PATHXORGXRDP="https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.2.12/xorgxrdp-0.2.12.tar.gz"
PATHSFML="https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip"
PATHWXGTK3="https://github.com/wxWidgets/wxWidgets/archive/v3.0.4/wxWidgets-3.0.4.tar.gz"
PATHVBAM="https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.1.4/visualboyadvance-m-2.1.4.tar.gz"
PATHFBIDA="https://www.kraxel.org/releases/fbida/fbida-2.14.tar.gz"
PATHOPENCV="https://github.com/opencv/opencv/archive/4.4.0/opencv-4.4.0.tar.gz"
PATHOPENCVBIS="https://github.com/opencv/opencv_contrib/archive/4.4.0/opencv_contrib-4.4.0.tar.gz"
PATHDISCORD="https://discordapp.com/api/download?platform=linux&format=deb"
PATHVLCYOUTUBE="https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua"
PATHMLT="https://github.com/mltframework/mlt/archive/v6.26.1.tar.gz"
PATHLIBCACA="http://caca.zoy.org/files/libcaca/libcaca-0.99.beta19.tar.gz"
PATHLIBWEBP="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz"
PATHEIGEN3='https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2'
PATHPAJACKCON='https://github.com/brummer10/pajackconnect/archive/master.tar.gz'

# Path which are in package.info file inside the package.
# TODO : Should be updated from those PATH or the SlackBuilds from SBo updated.

PATHSBO='https://slackbuilds.org/slackbuilds/14.2'

PATHROCCATTOOLS="http://downloads.sourceforge.net/roccat/roccat-tools-5.9.0.tar.bz2"
PATHKAFFEINE="https://github.com/KDE/kaffeine/archive/master.zip"
PATHGRADLE="https://services.gradle.org/distributions/gradle-6.2.2-all.zip"
PATHAUDIVERIS="https://github.com/Audiveris/audiveris/archive/master.zip"
PATHSIGNALDESKTOP="https://sourceforge.net/projects/slackbuildsdirectlinks/files/signal-desktop/signal-desktop_1.40.1_amd64.deb"
PATHVOKOSCREEN="https://github.com/vkohaupt/vokoscreenNG/archive/3.0.3.tar.gz"
PATHZOOM="https://zoom.us/client/latest/zoom_x86_64.tar.xz"
PATHOPENSHOT='https://launchpad.net/openshot/1.4/1.4.3/+download/openshot-1.4.3.tar.gz'
# A renommer en openshot_qt pour eviter les conflits avec openshot 1.4
# "multimedia/openshot.tar.gz"
PATHOPENSHOT2="https://github.com/OpenShot/openshot-qt/archive/v2.5.1/openshot-qt-2.5.1.tar.gz"
# python3-certify : compile only. No modifs.
# "python/python3-certifi.tar.gz"
PATHPYTHON3CERTIFY="https://pypi.python.org/packages/source/c/certifi/certifi-2019.6.16.tar.gz"
# "graphics/inkscape.tar.gz'
PATHINKSCAPE='https://inkscape.org/gallery/item/13330/inkscape-0.92.4.tar.bz2'
# "graphics/Blender.tar.gz'
PATHBLENDER='https://download.blender.org/source/blender-2.83.8.tar.xz'
# "graphics/openimageio.tar.gz'
PATHOPENIMAGEIO='https://github.com/OpenImageIO/oiio/archive/Release-2.0.13/oiio-Release-2.0.13.tar.gz'
# "graphics/opencolorio.tar.gz'
PATHOPENCOLORIO='https://github.com/imageworks/OpenColorIO/archive/v1.1.1/OpenColorIO-1.1.1.tar.gz'
# "python/pybind11.tar.gz'
PATHPYBIND11='https://github.com/pybind/pybind11/archive/v2.5.0/pybind11-2.5.0.tar.gz'
# "development/numpy3.tar.gz'
PATHNUMPY3='https://github.com/numpy/numpy/releases/download/v1.19.2/numpy-1.19.2.tar.gz'
# "libraries/tbb.tar.gz'
PATHTBB='https://github.com/oneapi-src/oneTBB/archive/2020_U2/tbb-2020_U2.tar.gz'
# "python/lxml.tar.gz'
PATHLXML='https://pypi.io/packages/source/l/lxml/lxml-4.4.1.tar.gz'
PATHOPERA='https://get.geo.opera.com/pub/opera-beta/72.0.3815.133/linux/opera-beta_72.0.3815.133_amd64.deb'

# KDE5 Frameworks. stable pour les derniers, Attic pour les plus vieux.
KDE5_FW_SRC='https://download.kde.org/Attic/frameworks/5.81'
KDE5_PLASMA_WAYLAND='https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-v1.2.1.tar.xz'
