#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# List of aspire links for KDE4.
# Some source packages are in build/src

KDE4OTHER_SCIMTABLES='https://sourceforge.net/projects/scim/files/scim-tables/0.5.14/scim-tables-0.5.14.1.tar.gz/download'
KDE4OTHER_SCIMPINYIN='https://sourceforge.net/projects/scim/files/scim-pinyin/0.5.92/scim-pinyin-0.5.92.tar.xz/download'
KDE4OTHER_SOPRANO='https://sourceforge.net/projects/soprano/files/Soprano/2.9.4/soprano-2.9.4.tar.bz2/download'
KDE4OTHER_GLADE3='https://download.gnome.org/sources/glade3/3.8/glade3-3.8.6.tar.xz'
KDE4OTHER_QT='https://download.qt.io/archive/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz'
KDE4OTHER_QTWEBKIT='https://download.kde.org/stable/qtwebkit-2.3/2.3.4/src/qtwebkit-2.3.4.tar.gz'
KDE4OTHER_PYQT='https://www.riverbankcomputing.com/static/Downloads/PyQt4/4.12.3/PyQt4_gpl_x11-4.12.3.tar.gz'
KDE4OTHER_QIMAGEBLITZ='https://download.kde.org/stable/qimageblitz/qimageblitz-0.0.6.tar.bz2'
KDE4OTHER_AUTOMOC4='https://download.kde.org/stable/automoc4/0.9.88/automoc4-0.9.88.tar.bz2'
KDE4DEPS_POPPLER='https://poppler.freedesktop.org/poppler-21.04.0.tar.xz'

KDE4_SRC='https://download.kde.org/Attic/4.14.3/src'
KDE4_KACTIVITIES='https://download.kde.org/Attic/4.13.3/src/kactivities-4.13.3.tar.xz'
KDE4_LIBKSCREEN='https://download.kde.org/stable/libkscreen/1.0.5/src/libkscreen-1.0.5.tar.xz'
KDE4_LIBKTORRENT='https://github.com/KDE/libktorrent/archive/v1.3.1.tar.gz'
KDE4_KTORRENT='https://github.com/KDE/ktorrent/archive/v4.3.1.tar.gz'
KDE4_CALLIGRA='https://download.kde.org/Attic/calligra-2.9.11'
KDE4_APPS='https://download.kde.org/Attic/applications/17.08.3/src'
KDE4_WORKSPACE='https://download.kde.org/Attic/applications/15.08.0/src/kde-workspace-4.11.22.tar.xz'
KDE4_AMAROK='https://download.kde.org/Attic/amarok/2.9.0/src/amarok-2.9.0.tar.xz'
KDE4_BLUEDEVIL='https://download.kde.org/stable/bluedevil/2.1.1/src/bluedevil-2.1.1.tar.xz'
KDE4_K3B='https://download.kde.org/stable/k3b/k3b-2.0.3.tar.xz'
KDE4_KAUDIOCREATOR='https://github.com/KDE/kaudiocreator/archive/master.tar.gz'
KDE4_KDECONNECT='https://download.kde.org/unstable/kdeconnect/0.8/src/kdeconnect-kde-0.8.tar.xz'
KDE4_KDEVPYTHON='https://download.kde.org/Attic/kdevelop/4.7.3/src/kdev-python-1.7.3.tar.bz2'
KDE4_KDEVELOP='https://download.kde.org/Attic/kdevelop/4.7.4/kdevelop-4.7.4.tar.xz'
KDE4_KDEVELOPPHP='https://download.kde.org/Attic/kdevelop/4.7.4/kdevelop-php-1.7.4.tar.xz'
KDE4_KDEVELOPPHPDOCS='https://download.kde.org/Attic/kdevelop/4.7.4/kdevelop-php-docs-1.7.4.tar.xz'
KDE4_KDEVPLATFORM='https://download.kde.org/Attic/kdevelop/4.7.4/kdevplatform-1.7.4.tar.xz'
KDE4_KIOMTP='https://github.com/KDE/kio-mtp/archive/master.tar.gz'
KDE4_KPLAYER='https://download.kde.org/stable/kplayer/0.7.2/src/kplayer-0.7.2.tar.xz'
KDE4_KSCREEN='https://download.kde.org/stable/kscreen/1.0.2.1/src/kscreen-1.0.2.1.tar.xz'
KDE4_KWEBKITPART='https://github.com/KDE/kwebkitpart/archive/v1.3.4.tar.gz'
KDE4_LIBMMQT='https://download.kde.org/unstable/modemmanager-qt/1.0.1/src/libmm-qt-1.0.1-1.tar.xz'
KDE4_OXYGENGTK2='https://download.kde.org/stable/oxygen-gtk2/1.4.6/src/oxygen-gtk2-1.4.6.tar.bz2'
KDE4_PARTITIONMANAGER='https://download.kde.org/stable/partitionmanager/1.1.1/src/partitionmanager-1.1.1.tar.xz'
KDE4_PLASMANM='https://download.kde.org/stable/plasma-nm/plasma-nm-0.9.3.6.tar.xz'
KDE4_SKANLITE='https://download.kde.org/stable/skanlite/1.1/src/skanlite-1.1.tar.xz'
KDE4_WICDKDE='https://github.com/KDE/wicd-kde/archive/v0.3.1.tar.gz'
KDE4_KDEVELOPPGQT='https://download.kde.org/stable/kdevelop-pg-qt/1.0.0/src/kdevelop-pg-qt-1.0.0.tar.bz2'
