#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xhelp () {
    echo 'Launch this script in a new directory.'
    echo 'or in a directory which contains slackware64-current.'
    echo
    echo 'pbslacks should be side by side of this current directory.'
    echo
    echo '> ../pbslacks/pbpostinstallarm [-help|-h]'
}

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

if [ $XTEST -ne 1 -a "$0" != "../pbslacks/$MYPROG" \
    -a "$0" != "pbslacks/$MYPROG" ] ;then
    xhelp
    exit 1
fi

set +e

if [ -d  /mnt/boot ] ;then
    ROOT=/mnt removepkg kernel_armv7 kernel-modules-armv7
    mount -t vfat /dev/mmcblk0p1 /mnt/boot 
    rm /mnt/boot/initrd.gz
    ROOT=/mnt installpkg /rpi-extra/kernel* /rpi-extra/sarpi*

    sed -i "s/^.*hdmi_drive=.*$/hdmi_drive=2/" /mnt/boot/config.txt
    sed -i "s/^.*dtparam=audio=.*$/dtparam=audio=on/" /mnt/boot/config.txt
    sed -i "s/^.*disable_overscan=.*$/disable_overscan=1/" /mnt/boot/config.txt

    if [ $(ls /usb-stick | wc -l) -ne 0 ] ;then
	umount /usb-stick # Remove the key.
	echo 'You can now remove the USB stick and reboot the computer.'
    else
	echo 'Unmount your USB stick and remove it before rebooting the computer.'
    fi
else
    mygt "I don't see your install. Do the extra work by hand."
fi

echo 'You can also edit /mnt/boot/config.txt ot /boot/config.txt after a reboot and tune some parameters'
