#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xhelp () {
    cat <<EOF
Script a lancer dans un repertoire contenant slackware64-current ou slackware64
  ou a partir du repertoire courant pour une nouvelle copie complete.

Launch this script in a directory which contains slackware64-current or slackware64
  or from the current directory for a new clone.
EOF
}

XTEST=0

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-test" ] ;then
	XTEST=1
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

MYPROG=$(basename "$0")

if [ $XTEST -ne 1 -a "$0" != "../pbslacks/$MYPROG" \
    -a "$0" != "pbslacks/$MYPROG" ] ;then
    xhelp
    exit 1
fi

# TODO
