#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

xhelp () {
    mygt 'Stop the hibernate mode of the Windows partitions.'
    echo
    echo "> [../]pbslack/pbstophy"
}

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-test" ] ;then
	XTEST=1
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

if [ ! $UID = 0 ]; then
    mygt 'This script must be done as root. Exit.'
    exit 1
fi

cd "$MYPWD"
BAN=0xFE11C1A
if [ -L /dev/disk/by-label/USBSLACK ]; then
    BAN="$(readlink -f /dev/disk/by-label/USBSLACK)"
fi
if [ -L /dev/disk/by-label/USBSLACKINS ]; then
    BAN="$(readlink -f /dev/disk/by-label/USBSLACKINS | cut -b 1-8)"
fi
DOSLIST="$($PBDIRPROG/probe -l 2> /dev/null |\
	grep -E "DOS|Win(95 F|98 F)|HPFS|W95 F|FAT(12|16)|Microsoft basic data" |\
	grep -Ev "Ext('d|end)" | grep -v "$BAN" | sort)"

echo "$DOSLIST" | while read i ; do
    xdev=$(echo "$i"| cut -d ' ' -f1)
    rdev=$(echo "$xdev"| cut -c6-)
    type=$(lsblk -f $xdev|grep $rdev|tr -s ' '|cut -d ' ' -f2)
    echo "type = ${type},$xdev => $i"
    if [ $XTEST -eq 0 -a "$type" = 'ntfs' ] ;then
        ntfsfix $xdev
        mount -t ntfs-3g $xdev /mnt/hd -o remove_hiberfile
        umount /mnt/hd
	emygt "\$xdev hibernate removed."
    fi
done
