#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

if [ "$1" = '' ] ;then
    echo "Give the name of the device to unmount like /dev/loop0."
    exit 1
fi

XDEV="$1"

udisksctl unmount -b "${XDEV}p1"

if [ $? -ne 0 ] ;then
    udisksctl unmount -b "${XDEV}"
fi

udisksctl loop-delete -b "$XDEV"

echo "ISO unmounted."
