#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

FN="$0";[ "$0" = "$(basename $0)" ] && FN=$(which "$0")
PBSDIR=$(dirname "$(readlink -f "$FN")")
. "$PBSDIR/pbinclude"

xhelp () {
    mygt "Give the name of the device to unmount like /dev/loop0."
    echo
    echo "> $(basename $0) /dev/loop0"
}

if [ "$1" = '' ] ;then
    xhelp
    exit 1
fi

XDEV="$1"

xunmount () {
    XL="$1"
    udisksctl unmount -b "$XL"
}

xunlosetup () {
    XL="$1"
    udisksctl loop-delete -b "$XL"
}

if [ -b "${XDEV}p1" ] ;then
    xunmount "${XDEV}p1"
elif [ ! -f "${XDEV}p1" -a -b "${XDEV}" ] ;then
    xunmount "${XDEV}"
else
    xhelp
    exit 1
fi

if [ $? -eq 0 ] ;then
    mygt "Device unmounted."
fi

if [ "$(echo "$XDEV"|cut -c1-9)" = "/dev/loop" ] ;then
    mygt "Loop device detached."
    xunlosetup "$XDEV"
fi
