#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

if [ ! $UID = 0 ]; then
    mygt 'This script must be done as root. Exit.'
    exit 1
fi

xhelp () {
    mygt 'Launch this script in the directory including alreadey cloned slackware64 or slackware64-current.\nIt can be on the bootable slackware install USB stick.\npbslacks should also be there.'|sed 's@\\n@\n@g'
    echo
    echo "  > cd .../slackware-current"
    echo "or> cd /run/media/$USER/USBSLACKINS/SlackDVD"
    echo '  > pbslacks/pbupgradebumblebee'
}

[ -d "$SLACKREPO" ] && cd "$SLACKREPO"
if [ ! -d "$SLACKSUBDIR" -o '(' ! -h pbslacks -a ! -d pbslacks ')' ] ;then
    xhelp
    exit 1
fi

MYPWD=$(pwd)
HOMESLACK="$MYPWD"

mygt 'Only for NVDIA second card on laptop.\nUpdate eventually Bumblebee with pbcompilebumblebee which update also.\nPress a touch for continue or abort.'|sed 's@\\n@\n@g'
read c

cd $HOMESLACK
upgradepkg --install-new bumblebee/*.t?z
[ -x /etc/rc.d/rc.bumblebee ] && /etc/rc.d/rc.bumbleebee restart

mygt "Upgrade bumblebee done."
