#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xhookopenshot () {
    # Post actions for openshot
    rm -rf packages/python-pillow
    rm -f packages/openshot/frei0r-plugins-1.4-x86_64-2dj.*
    rm -rf packages/openshot/python3-certifi
    rm -f packages/openshot/python3-certifi-2019.6.16-x86_64-1_SBo.*
    rm -f packages/openshot/libopenshot-0.2.5-x86_64-1ponce.*
    rm -f packages/openshot/dos2unix-7.4.2-x86_64-2cf.*
    rm -f packages/openshot/double-conversion-3.1.7-x86_64-1cf.*
    rm -f packages/openshot/potrace-1.16-x86_64-2cf.*
    rm -f packages/openshot/gdl-3.40.0-x86_64-1cf.*
    rm -f packages/openshot/graphicsmagick-1.3.37-x86_64-1cf.*
    rm -f packages/openshot/libvdpau-va-gl-0.4.2-x86_64-1dj.*
    removepkg frei0r-plugins
    removepkg python3-certifi
    removepkg graphicsmagick
    upgradepkg --reinstall slackware64/l/python-certifi-*.t?z
}

xhookpitivi () {
    # Post actions for pitivi
    rm -rf packages/pitivi/python3-six
    rm -f packages/pitivi/python3-six-*-x86_64-1_SBo.*
    removepkg python3-six
    upgradepkg --reinstall slackware64/l/python-six-*.t?z
}

xhookdebian () {
    # Post actions for debian
    echo "none" > /dev/null
}

xhookpac1 () {
    # Post actions for packages
    upgradepkg --reinstall slackware64/ap/linuxdoc-tools-*.t?z
#    upgradepkg --reinstall packages/glibc-*alien.t?z
    removepkg phonon4qt5
    removepkg OpenAL
    removepkg OpenAL-compat32
    rm -f packages/openal-soft-1.*_SBo.tgz
    rm -f packages/*_slonly.*
    rm -f packages/32/wxPython-2.8.12.1-i486-3dj.*
}

xhookpac2 () {
    # Post actions for packages2
    upgradepkg --reinstall slackware64/l/oniguruma-*.t?z
    cp packages2/youtube.lua $XLIBDIR/vlc/lua/playlist
    rm -f $XLIBDIR/vlc/lua/playlist/youtube.luac
    rm -f packages2/discord-*.tar.gz
    rm -f packages2/*_slonly.*
    rm -f packages2/valgrind-3.18.1-x86_64-1cf.*
    rm -f packages2/jq-1.6-x86_64-2cf.*
    rm -f packages2/lua53-5.3.6-x86_64-1cf.*
    rm -f package2/lua-5.4.3-x86_64-1cf.*
    rm -f package2/oniguruma-6.9.2-x86_64-1cf.*
    rm -f package2/guile1.8-1.8.8-x86_64-1dj.*
    rm -f package2/gnome-desktop-3.36.6-x86_64-1dl.*
    rm -f package2/webkitgtk-2.28.4-x86_64-1dl.*
    rm -f package2/libseccomp-2.4.2-x86_64-1dl.*
}

xhookpac3 () {
    # Post actions for packages3
    echo "none" > /dev/null
}

xhookcalibre () {
    # Post actions for packages3
    rm -f calibre-4.15.0-x86_64-1alien.txz.*
}

xhookkde4 () {
    # Post actions for kde4
    # Reput the current one. It has been modified by deps for compilation.
    upgradepkg --reinstall slackware64/l/sip-*.txz
}

xhookkde4deps () {
    # Post actions for kde4
    # Reput the current one. It has been modified by deps for compilation.
    removepkg attica
}

xhookframew () {
    # Post actions for framew
    echo "none" > /dev/null
}

xhookpac4 () {
    # For H264 and DRM support for Opera.
    if [ -f $XLIBDIR/chromium/libffmpeg.so ] ;then
	if [ -d $XLIBDIR/opera ] ;then
	    mv -f $XLIBDIR/opera/libffmpeg.so $XLIBDIR/opera/libffmpeg.so.bak
	    ln -sf $XLIBDIR/chromium/libffmpeg.so $XLIBDIR/opera
	fi
	if [ -d $XLIBDIR/opera-beta ] ;then
	    mv -f $XLIBDIR/opera-beta/libffmpeg.so \
	       $XLIBDIR/opera-beta/libffmpeg.so.bak
	    ln -sf $XLIBDIR/chromium/libffmpeg.so $XLIBDIR/opera-beta
	fi
    fi
    if [ -f $XLIBDIR/chromium/libwidevinecdm.so ] ;then
	[ -d $XLIBDIR/opera ] && \
	    ln -sf $XLIBDIR/chromium/libwidevinecdm.so $XLIBDIR/opera
	[ -d $XLIBDIR/opera-beta ] && \
	    ln -sf $XLIBDIR/chromium/libwidevinecdm.so $XLIBDIR/opera-beta
    fi
}

xhooktess () {
    cp packages4/tesseract4/xsane2tess* /usr/bin
}

# Some config I always use.
myconfig () {
    if [ -d /etc/profile.d ] ; then
	cp pbslacks/LocaleFR/csh.cshrc /etc
	cp pbslacks/LocaleFR/pbalias.sh /etc/profile.d
	XLANG=$(echo $LANG|cut -d '.' -f1|cut -d '_' -f1)
	if [ "$XLANG" = 'fr' ] ;then
	    cp pbslacks/LocaleFR/lang.* /etc/profile.d
	    KBX11=90-keyboard-layout-evdev.conf
	    [ ! -f /etc/X11/xorg.conf.d/$KBX11 ] && \
		cp pbslacks/LocaleFR/$KBX11 /etc/X11/xorg.conf.d
	fi
    fi
    # Bug with KDE 4 and Pulseaudio.
    cat pbslacks/builds/start-pulseaudio-x11.patch|(cd /usr/bin;patch -f -p0)
}
