#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019

if [ ! $UID = 0 ]; then
  cat << EOF
This script must be run as root.
EOF
  exit 1
fi

if [ ! -d slackware64-current ] ;then
    echo "Script a lancer dans le repertoire contenant slackware64-current fraichement aspire."
    exit 1
fi

MYPWD=`pwd`
HOMESLACK="$MYPWD"
XNEW="$1"

if [ "$XNEW" = '' ] ;then
    cp pbslacks/Slackpkg/blacklist /etc/slackpkg
    cp pbslacks/Slackpkg/slackpkg.conf /etc/slackpkg
    cat pbslacks/Slackpkg/mirrors | sed "s@HOMESLACK@${HOMESLACK}@" > /etc/slackpkg/mirrors
    slackpkg update gpg
    slackpkg update
    slackpkg install-new
    slackpkg upgrade-all
    slackpkg clean-system

    if [ $? -ne 0 ] ;then
	echo 'Abort : voir erreurs precedentes.'
    fi
    echo "Upgrade fait."
fi

cd $HOMESLACK
upgradepkg --reinstall --install-new current/*.t?z
upgradepkg --install-new current/slackware64-compat32/*/*.t?z
echo "Upgrade multilib fait."

cd $HOMESLACK
upgradepkg --install-new packages*/*.t?z
upgradepkg --install-new packages4/frameworks/*.t?z
upgradepkg --install-new packages4/audacity/*.t?z
upgradepkg --install-new packages4/tesseract4/*.t?z
cp packages4/tesseract/xsane2tess* /usr/bin
echo "Upgrade packages* fait."

$HOMESLACK/pbslacks/pbupgrademoz

if [ -d /boot/efi/EFI/Slackware ] ;then
  echo "Boot UEFI detected, y or n ?"
  read c
  if [ "$c" = 'y' ] ;then
    cp /boot/vmlinuz /boot/initrd.gz /boot/efi/EFI/Slackware
    echo "Files vmlinuz et initrd.gz copied in /boot/efi/EFI/Slackware"
  fi
elif [ -f /boot/grub/grub.cfg ] ;then
  echo "Boot Grub detected, y or n ?"
  read c
  if [ "$c" = 'y' ] ;then
    grub-mkconfig -o /boot/grub/grub.cfg
    echo "Grub updated"
  fi
elif [ -f /etc/lilo.conf ] ;then
  echo "Boot Lilo detected, y or n ?"
  read c
  if [ "$c" = 'y' ] ;then
    /sbin/lilo
    echo "Lilo updated"
  fi
fi

echo "Redémarrer la machine puis si necessaire remettez Crazybee"
if [ "$c" != 'y' ] ;then
  echo "If lilo is installed, launch : /sbin/lilo"
  echo "If Grub is installed, launch : grub-mkconfig -o /boot/grub/grub.cfg"
  echo "If Boot UEFI ELILO is installed, do :"
  echo "  cp /boot/vmlinuz /boot/initrd.gz /boot/efi/EFI/Slackware"
fi

echo "Ensuite lancez si pas deja fait sur une machine mise a jour :"
echo "  pbslacks/pbinstallpost"
echo "Si votre machine est un portable avec 2 cartes graphiques dont 1 NVIDIA, relancez :"
echo "  pbslacks/pbinstallcrazybee"
