#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

if [ ! $UID = 0 ]; then
    mygt 'This script must be done as root. Exit.'
    exit 1
fi

xhelp () {
    mygt 'Launch this script in the directory including alreadey cloned slackware64 or slackware64-current.\nIt can be on the bootable slackware install USB stick.\npbslacks should also be there.'|sed 's@\\n@\n@g'
    echo
    echo "  > cd .../slackware-current"
    echo "or> cd /run/media/$USER/USBSLACKINS/SlackDVD"
    echo "  > pbslacks/pbupgrademoz"
}

if [ -d slackware64-${SLACKVER} ] ;then
    cd slackware64-${SLACKVER}
fi
if [ ! -d slackware64 -o '(' ! -h pbslacks -a ! -d pbslacks ')' ] ;then
    xhelp
    exit 1
fi

MYPWD=$(pwd)
HOMESLACK="$MYPWD"
HOMEMOZ="$XLIBDIR"

FFVERSION=$(ls "$HOMESLACK/packages/Mozilla/firefox-"*"esr.tar.bz2" 2> /dev/null)
THVERSION=$(ls "$HOMESLACK/packages/Mozilla/thunderbird-"*".tar.bz2" 2> /dev/null)

installmoz () {
    PROD="$1"
    VERSION="$2"
    if [ -s "$VERSION" ] ;then
	rm -rf $HOMEMOZ/${PROD}.en
	mv $HOMEMOZ/$PROD $HOMEMOZ/${PROD}.en
	cd $HOMEMOZ
	tar xfj "$VERSION"
    fi
}

installmoz firefox "$FFVERSION"
installmoz thunderbird "$THVERSION"

mygt "Firefox et Thunderbird added."
cd "$MYPWD"
