#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"

xhelp () {
    mygt 'Launch this script in the directory including alreadey cloned slackware64 or slackware64-current.\nIt can be on the bootable slackware install USB stick.\npbslacks should also be there.'|sed 's@\\n@\n@g'
    echo
    echo '  > cd .../Slackware-x64-date'
    echo 'or> cd /run/media/$USER/USBSLACKINS/SlackDVD'
    echo '  > pbslacks/pbupgrade [-new (no system update)]'
    echo '       [-test (test only, no actions)] [-help|-h] [-nodial]'
    echo '       [-post (actions to do preferably after a postinstall reboot)]'
}

XNEW=
XPOST=
MYUSER=produits
MYGROUP=users

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-new" ] ;then
	XNEW=yes
    elif [ "$MYARG" = "-nodial" ] ;then
	ISDIAL=0
    elif [ "$MYARG" = "-test" ] ;then
	XTEST=1
    elif [ "$MYARG" = "-post" ] ;then
	XPOST=yes
    elif [ "$MYARG" = "-u" ] ;then
	shift
	MYUSER="$1"
    elif [ "$MYARG" = "-g" ] ;then
	shift
	MYGROUP="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware/slackware64-current/'
XTEMPOUT=$(mktemp -p /tmp -t pbupgradeout.XXXXXX)
XTEMPMES=$(mktemp -p /tmp -t pbupgrademes.XXXXXX)

# Upgrade with the main stream package.
xupmainpac () {
    pac="$1"
    suf="$2"
    repo="$3"
    grp="$4"
    dir="$5"
    [ $(ls /var/log/$dir/${pac}*-$repo.$suf|wc -l) -eq 1 ] &&\
	upgradepkg slackware64/$grp/${pac}*$suf
}

cleanup () {
    rm -f $XTEMPOUT
    rm -f $XTEMPMES
}

trap 'echo "*** Ctrl-C caught -- aborting operations ***"; cleanup; exit 1' 2 14 15 # trap Ctrl-C and kill

if [ ! -d /boot ] ;then
    mygt "Do the install of the Slackware Linux distribution before :\n-see the doc/SLACKWARE.txt file." |sed 's@\\n@\n@g' > $XTEMPMES
fi

if [ $XTEST -ne 1 ] ;then
    if [ -d slackware64-current ] ;then
	cd slackware64-current
    fi
    if [ ! -d slackware64 -o '(' ! -h pbslacks -a ! -d pbslacks ')' ] ;then
	mygt 'slackware64 or pbslacks not found.'> $XTEMPMES
	xhelp >> $XTEMPMES
    fi
fi

if [ -s "$XTEMPMES" ] ;then
    dialog --colors --backtitle 'pbupgrade' --title 'End messages' \
	--msgbox "$(cat $XTEMPMES)" 20 85
    cleanup
    exit 1
fi

DACTION=$(mygt 'Actions which were done')

if [ $XTEST -ne 1 ] ;then
    if [ ! $UID = 0 ]; then
        mygt 'This script must be done as root. Exit.' > $XTEMPMES
        dialog --colors --backtitle 'pbupgrade' --title "$DACTION" \
	    --msgbox "$(cat $XTEMPMES)" 20 80
	cleanup
	exit 1
    fi
fi

MYPWD=$(pwd)
HOMESLACK="$MYPWD"

if [ "$XNEW" = 'yes' ] ;then
    XUPSYSTEM=off
else
    XUPSYSTEM=on
fi

if [ "$XPOST" = 'yes' ] ;then
    XUPNOPOST=off
    XUPPOST=on
    XUPSYSTEM=off
else
    XUPPOST=off
    XUPNOPOST=on
fi

xmaster () {
    defitem=$1;shift
    xsel1=$1;shift;xsel2=$1;shift;xsel3=$1;shift;xsel4=$1;shift;xsel5=$1;shift
    xsel6=$1;shift;xsel7=$1;shift;xsel8=$1;shift;xsel9=$1;shift;xsel10=$1;shift
    xsel11=$1;shift;xsel12=$1;shift;xsel13=$1;shift;xsel14=$1
    pactit=$(mygt 'Main menu')
    pactit="pbupgrade: $pactit"
    dialog --colors --backtitle 'pbupgrade' --title "$pactit" \
	--default-item $defitem --defaultno \
	--separate-output --item-help --help-button --help-status --checklist \
	"$(mygt 'Choose your actions below after you have launch the \Zbpbaspire*\ZB script')" 0 100 14 \
	system "$(mygt 'Sync/Update system to the last fetched current Slackware')" $xsel1 system \
	systemnet "$(mygt 'Sync/Update system to the last current Slackware on the internet')" $xsel2 systemnet \
	compat32 "$(mygt 'Install/Update the 32 bits compatible mode')" $xsel3 compat32 \
	mozilla "$(mygt 'Install/Update the Firefox and Thunderbird softwares')" $xsel4 mozilla \
	packages "$(mygt 'Install/Update the packages set of software')" $xsel5 packages \
	packages2 "$(mygt 'Install/Update the packages2 set of software')" $xsel6 packages2 \
	packages3 "$(mygt 'Install/Update the packages3 set of software')" $xsel7 packages3 \
	packages4 "$(mygt 'Install/Update the packages4 set of software')" $xsel8 packages4 \
	frameworks "$(mygt 'Install/Update the KDE5 frameworks libraries')" $xsel9 frameworks \
	audacity "$(mygt 'Install/Update the Audacity software')" $xsel10 audacity \
	tesseract4 "$(mygt 'Install/Update the Tesseract version 4 software')" $xsel11 tesseract4 \
	bumblebee "$(mygt 'Install/Update the Bumblebee support of your second NVIDIA graphic card')" $xsel12 bumblebee \
	recreate "$(mygt 'Compile again some packages.')" $xsel13 recreate \
	recreatebumblebee "$(mygt 'Compile again Bumblebee packages.')" $xsel14 recreatebumblebee
}

xpacaide () {
    packages="$1"
    pacaide="Update the $packages set of tools :"
    ls -1 "$packages/"*.t?z > $XTEMPMES
    while read j;test "$j" != "" ;do
	pacaide="${pacaide}\n$j"
    done < $XTEMPMES
    rm -f $XTEMPMES
}

xsel="$XUPSYSTEM off $XUPNOPOST $XUPNOPOST $XUPNOPOST $XUPNOPOST $XUPNOPOST \
$XUPNOPOST $XUPNOPOST $XUPNOPOST $XUPNOPOST $XUPPOST $XUPPOST $XUPPOST"
ditem=system
bclaide=1

while [ $bclaide -eq 1 ] ;do
    xmaster $ditem $xsel 2> $XTEMPOUT
    bclaide=$(cat $XTEMPOUT|grep '^HELP'|wc -l)
    if [ $bclaide -eq 1 ] ;then
	xitem="$(cat $XTEMPOUT|grep '^HELP'|cut -d ' ' -f2)"
	xsel=
	for i in system systemnet compat32 mozilla packages packages2 packages3 \
	    packages4 frameworks audacity tesseract4 bumblebee recreate \
	    recreatebumblebee ;do
	  if [ $(grep "^$i$" "$XTEMPOUT"|wc -l) -eq 1 ] ;then
	      xsel="$xsel on"
	  else
	      xsel="$xsel off"
	  fi
	done
	ditem=$xitem;bclaide=1;pacaide=
	if [ "$xitem" = system ] ;then
	    pacaide=$(mygt 'Upgrade your Slackware system with the last current fetched.\nUses Slackpkg.')
	elif [ "$xitem" = systemnet ] ;then
	    pacaide=$(mygt 'Upgrade your Slackware system with the last current on the internet.\nUses Slackpkg.')
	elif [ "$xitem" = compat32 ] ;then
	    pacaide=$(mygt 'Upgrade the Alien Bob 32 bits compatible mode.')
	elif [ "$xitem" = mozilla ] ;then
	    pacaide=$(mygt 'Upgrade the Firefox and Thunderbird products.\nThey should be downloaded and put in the packages/Mozilla directory before.')
	elif [ "$(echo "$xitem"|cut -c1-8)" = packages ] ;then
	    xpacaide "$xitem"
	elif [ "$xitem" = frameworks ] ;then
	    xpacaide packages4/frameworks
	elif [ "$xitem" = audacity ] ;then
	    xpacaide packages4/audacity
	elif [ "$xitem" = tesseract4 ] ;then
	    xpacaide packages4/tesseract4
	elif [ "$xitem" = bumblebee ] ;then
	    pacaide=$(mygt 'Upgrade your Bumblebee packages if they are in sync with the upgraded Slackware.\nDone on another machine for exemple.')
	elif [ "$xitem" = recreate ] ;then
	    pacaide=$(mygt 'Redo the packages which are here in sources form.\nIf not already done on this machine or another.')
	elif [ "$xitem" = recreatebumblebee ] ;then
	    pacaide=$(mygt 'Redo the Bumblebee packages.\nIf not already done on this machine or another.\nYou should reboot after upgrading system packages and before doing this action else the Bumblebee packages wont built.')
	fi
	dialog --colors --backtitle 'pbupgrade' --title "$xitem" \
	    --msgbox "$pacaide" 20 80
    fi
done

XEND=0
ISSYSTEM="$(cat $XTEMPOUT|grep '^system$'|wc -l)"
ISSYSNET="$(cat $XTEMPOUT|grep '^systemnet$'|wc -l)"
ISCOMPAT="$(cat $XTEMPOUT|grep '^compat32$'|wc -l)"
ISMOZ="$(cat $XTEMPOUT|grep '^mozilla$'|wc -l)"
ISPACK="$(cat $XTEMPOUT|grep '^packages$'|wc -l)"
ISPACK2="$(cat $XTEMPOUT|grep '^packages2$'|wc -l)"
ISPACK3="$(cat $XTEMPOUT|grep '^packages3$'|wc -l)"
ISPACK4="$(cat $XTEMPOUT|grep '^packages4$'|wc -l)"
ISFRAME="$(cat $XTEMPOUT|grep '^frameworks$'|wc -l)"
ISAUDACITY="$(cat $XTEMPOUT|grep '^audacity$'|wc -l)"
ISTESS="$(cat $XTEMPOUT|grep '^tesseract4$'|wc -l)"
ISBUMBLE="$(cat $XTEMPOUT|grep '^bumblebee$'|wc -l)"
ISRECRE="$(cat $XTEMPOUT|grep '^recreate$'|wc -l)"
ISRECREBUMBLE="$(cat $XTEMPOUT|grep '^recreatebumblebee$'|wc -l)"

if [ $ISSYSTEM -eq 1 -o $ISSYSNET -eq 1 ] ;then
    if [ $XTEST -ne 1 ] ;then
	cp pbslacks/Slackpkg/blacklist /etc/slackpkg
        if [ $ISSYSTEM -eq 1 ] ;then
	    cat pbslacks/Slackpkg/slackpkg.conf | sed "s@CHECKGPG=on@CHECKGPG=off@" \
		    > /etc/slackpkg/slackpkg.conf
	    cat pbslacks/Slackpkg/mirrors | sed "s@HOMESLACK@${HOMESLACK}@" \
		    > /etc/slackpkg/mirrors
	else
	    cp pbslacks/Slackpkg/slackpkg.conf /etc/slackpkg
	    cat pbslacks/Slackpkg/mirrors | \
		    sed "s@^.*HOMESLACK.*\$@${SLACKMIR}@" > /etc/slackpkg/mirrors
	fi
	slackpkg update gpg
	slackpkg update
	slackpkg install-new
	slackpkg upgrade-all
	slackpkg clean-system

	if [ $? -ne 0 ] ;then
	    rm -f $XTEMPOUT
	    which slackpkg 2> $XTEMPMES
	    mygt 'Abort : see previous errors.' >> $XTEMPMES
	    mygt "Upgrade system not done." >> $XTEMPMES
	    XEND=1
	else
            xupmainpac "libxkbcommon-" t?z alien l packages
            xupmainpac "qt5-[0-9]" t?z alien l packages
            xupmainpac "qt5-webkit-[0-9]" t?z alien l packages
            xupmainpac "PyQt5-[0-9]" t?z alien l packages4
	    mygt "Upgrade system done." >> $XTEMPMES
	fi

    else
	mygt "Upgrade system done." >> $XTEMPMES
    fi
fi
if [ $XEND -eq 0 ] ;then
    if [ $ISCOMPAT -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --reinstall --install-new current/*.t?z
	    upgradepkg --install-new current/slackware64-compat32/*/*.t?z
	fi
	mygt "Upgrade Alien Bob multilib done." >> $XTEMPMES
    fi
    if [ $ISMOZ -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    $HOMESLACK/pbslacks/pbupgrademoz
	fi
	mygt "Upgrade Mozilla done." >> $XTEMPMES
    fi
    if [ $ISPACK -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages/*.t?z
	    upgradepkg --install-new packages/compat32/*.t?z
	fi
	mygt "Upgrade packages done." >> $XTEMPMES
    fi
    if [ $ISPACK2 -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages2/*.t?z
	    upgradepkg --install-new --reinstall packages2/*master*.t?z
            cp packages2/youtube.lua /usr/lib64/vlc/lua/playlist
	fi
	mygt "Upgrade packages2 done." >> $XTEMPMES
    fi
    if [ $ISPACK3 -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages3/*.t?z
	fi
	mygt "Upgrade packages3 done." >> $XTEMPMES
    fi
    if [ $ISPACK4 -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages4/*.t?z
	fi
	mygt "Upgrade packages4 done." >> $XTEMPMES
    fi
    if [ $ISFRAME -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages4/frameworks/*.t?z
	    upgradepkg --install-new --reinstall packages4/*master*.t?z
	fi
	mygt "Upgrade frameworks done." >> $XTEMPMES
    fi
    if [ $ISAUDACITY -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages4/audacity/*.t?z
	fi
	mygt "Upgrade audacity done." >> $XTEMPMES
    fi
    if [ $ISTESS -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradepkg --install-new packages4/tesseract4/*.t?z
	    cp packages4/tesseract4/xsane2tess* /usr/bin
	fi
	mygt "Upgrade tesseract4 done." >> $XTEMPMES
    fi
    if [ $ISBUMBLE -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    $HOMESLACK/pbslacks/pbupgradebumblebee
	fi
	mygt "Upgrade Bumblebee done." >> $XTEMPMES
    fi
    if [ $ISRECRE -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    $HOMESLACK/pbslacks/pbcompilepost -u $MYUSER -g $MYGROUP
	fi
	mygt "Recreate source packages done." >> $XTEMPMES
    fi
    if [ $ISRECREBUMBLE -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    $HOMESLACK/pbslacks/pbcompilebumblebee -u $MYUSER -g $MYGROUP
	fi
	mygt "Recreate source Bumblebee done." >> $XTEMPMES
    fi
fi

if [ ! -f "$XTEMPMES" -o ! -s "$XTEMPMES" ] ;then
    mygt "No action was demanded. Exit." > $XTEMPMES
    XEND=1
fi

dialog --colors --backtitle 'pbupgrade' --title "$DACTION" \
    --msgbox "$(cat $XTEMPMES)" 20 80
cleanup

if [ $XEND -eq 1 ] ;then
    exit 0
fi

if [ $ISSYSTEM -eq 1 ] ;then
# Only if system was modified
    if [ -d /boot/efi/EFI/Slackware ] ;then
	xitem=elilo
    elif [ -f /boot/grub/grub.cfg ] ;then
	xitem=grub
    elif [ -f /etc/lilo.conf ] ;then
	xitem=lilo
    elif [ -f /syslinux.cfg ] ;then
	xitem=syslinux
    else
	xitem=none
    fi
    pactit=$(mygt 'Bootloader menu')
    pactxt=$(mygt 'We have detected the bootloader below. Cancel if it is not true.\nIn this last case, you should recreate the config of your bootloader before reboot. Else you will have to boot from another media as a DVD or an USB stick and rerun the install of your bootloader.')
    pacnone=$(mygt 'No bootloader detected. Reconfigure your bootloader before reboot.')
    dialog --colors --backtitle 'pbupgrade' --title "$pactit" \
	--default-item $xitem --menu "$pactxt" 15 80 5 \
	elilo 'Boot Elilo : /boot/efi/EFI/Slackware' \
	grub 'Boot Grub : /boot/grub/grub.cfg' \
	lilo 'Boot Lilo : /etc/lilo.conf' \
	syslinux 'Boot Syslinux : /syslinux.cfg' \
	none "$pacnone"\
	2> $XTEMPOUT
    xitem=$(cat $XTEMPOUT)

    xmes1 () {
	mygt "\ZbThe boot loader was not updated.\ZB\nIf lilo is installed, launch : \Z3/sbin/lilo\Zn\nIf Grub is installed, launch : \Z3grub-mkconfig -o /boot/grub/grub.cfg\Zn\nIf Syslinux is installed, launch : \Z3syslinux BOOTDEVICE\Zn\nIf Boot UEFI ELILO is installed, do :\n  \Z3cp /boot/vmlinuz /boot/initrd.gz /boot/efi/EFI/Slackware\Zn\n\n\ZbOr rerun your other favorite bootloader install procedure before rebooting.\ZB"
    }

    if [ "$xitem" = elilo -a -d /boot/efi/EFI/Slackware ] ;then
	mygt "Elilo updated : Files vmlinuz et initrd.gz copied in \Z3/boot/efi/EFI/Slackware\Zn" >> $XTEMPMES
	if [ $XTEST -ne 1 ] ;then
	    cp /boot/vmlinuz /boot/initrd.gz /boot/efi/EFI/Slackware
	fi
    elif [ "$xitem" = grub -a -f /boot/grub/grub.cfg ] ;then
	mygt "Grub updated : \Z3grub-mkconfig\Zn relaunched.\n\Z1Look if there are error messages below\Zn." >> $XTEMPMES
	if [ $XTEST -ne 1 ] ;then
	    grub-mkconfig -o /boot/grub/grub.cfg 2>> $XTEMPMES
	fi
    elif [ "$xitem" = lilo -a -f /etc/lilo.conf ] ;then
	mygt "Lilo updated with \Z3/sbin/lilo\Zn.\n\Z1Look if there are error messages below\Zn." >> $XTEMPMES
	if [ $XTEST -ne 1 ] ;then
	    /sbin/lilo 2>> $XTEMPMES
	fi
    elif [ "$xitem" = syslinux -a -f /syslinux.cfg ] ;then
	mygt "Look at \Z3/syslinux.cfg\Zn and rerun \Z3syslinux\Zn on your boot partition if some path have changed." >> $XTEMPMES
    else
	xmes1 >> $XTEMPMES
    fi

    if [ -f "$XTEMPMES" ] ;then
	dialog --colors --backtitle 'pbupgrade' --title 'Bootloader upgraded' \
	    --msgbox "$(cat $XTEMPMES)" 20 80
    fi

    cleanup
fi

if [ "$XNEW" != 'yes' ] ;then
    XBOOTMES=$(mygt ' (\Z1be sure to have updated the bootloader before\Zn)')
else
    XBOOTMES=
fi

xend () {
    emygt "Reboot the host\${XBOOTMES}.\n\n\ZbThen do if not already done on an already upgraded target :\ZB\nSelect '\Z3recreate\Zn' in the above menu after launching this script again.\n or do> \Z3pbslacks/pbcompilepost\Zn\n\n\ZbIf your host is a dual graphic card laptop with a NVIDIA card :\ZB\n  \Z4Do either :\Zn\n    Select '\Z3recreatebumblebee\Zn' in the above menu after launching this script again.\n    or do> \Z3pbslacks/pbcompilebumblebee\Zn\n  \Z4Or do only if already done on an upgraded target :\Zn\n    Select '\Z3bumblebee\Zn' in the above menu after launching this script again.\n    or do> \Z3pbslacks/pbupgradebumblebee\Zn"
}

xend >> $XTEMPMES

if [ -f "$XTEMPMES" ] ;then
    dialog --colors --backtitle 'pbupgrade' --title 'End messages' \
	--msgbox "$(cat $XTEMPMES)" 20 85
fi
rm -f $XTEMPMES
