#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

if [ ! $UID = 0 ]; then
  cat << EOF
This script must be run as root.
EOF
  exit 1
fi

xhelp () {
    cat <<EOF
Script a lancer dans un repertoire contenant slackware64-current.
Launch this script in a directory which contains slackware64-current.

pbslacks should be side by side of this current directory.
> pbslacks/pbupgradebumblebee
EOF
}

if [ ! -d slackware64-current ] ;then
    xhelp
    exit 1
fi

MYPWD=`pwd`
HOMESLACK="$MYPWD"

cat <<EOF
Only for NVDIA second card on laptop.
Seulement pour portable équipés d'une deuxième carte NVIDIA.
Mettez eventuellement Bumblebee a jour avec pbinstallbumblebee.
Appuyez sur une touche pour continuer - press a touch for continue or abort.
EOF
read c

cd $HOMESLACK
upgradepkg --install-new bumblebee/*.t?z
[ -x /etc/rc.d/rc.bumblebee ] && /etc/rc.d/rc.bumbleebee restart

echo "Upgrade bumblebee fait."
