#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# Upgrade with the main stream package.
xupmainpac () {
    pac="$1"
    suf="$2"
    repo="$3"
    grp="$4"
    [ $(ls /var/log/packages/${pac}*-[0-9]$repo 2> /dev/null|wc -l) -eq 1 ] &&\
	upgradepkg ${SLACKSUBDIR}/$grp/${pac}*$suf
}

# Upgradepkg with reinstall if the package date is newer than the installed
# one. I could have recompiled.
upgradedir () {
    xdir="$1"
    (
	cd "$xdir"
	ls *.t?z|while read i;test "$i" != "" ;do
	    upgradepkg --install-new "$i"
	    j=/var/log/packages/$(echo "$i"|sed 's/\.t.z$//')
	    [ "$i" -nt "$j" ] && upgradepkg --reinstall "$i"
	done
    )
}

setconfslackpkg () {
    xframe=on
    [ $(ls /var/log/packages/plasma-desktop-*[0-9]* 2> /dev/null|wc -l) -ge 1 ] \
	&& xframe=off
    
    [ $xframe = 'off' ] && \
	cp pbslacks/Slackpkg/blacklistkeepkde5 /etc/slackpkg/blacklist
    [ $xframe = 'on' ] && \
	cp pbslacks/Slackpkg/blacklistkeepkde4 /etc/slackpkg/blacklist
    
    SLPKGCONF=pbslacks/Slackpkg/slackpkg.conf
    [ "$(slackpkg |grep version|cut -d ' ' -f4|cut -c 1-3)" = '2.8' ] \
	&& SLPKGCONF=pbslacks/Slackpkg/slackpkg.conf.83
    
    if [ $ISSYSTEM -eq 1 ] ;then
	cat $SLPKGCONF | sed "s@CHECKGPG=on@CHECKGPG=off@" \
			     > /etc/slackpkg/slackpkg.conf
	cat pbslacks/Slackpkg/mirrors | sed "s@HOMESLACK@${HOMESLACK}@" \
					    > /etc/slackpkg/mirrors
    else
	cp $SLPKGCONF /etc/slackpkg
	cat pbslacks/Slackpkg/mirrors | \
	    sed "s@^.*HOMESLACK.*\$@${SLACKURL}@" > /etc/slackpkg/mirrors
    fi
}

upgradeglibc () {
    XCURDIRA=${SLACKSUBDIR}/a
    if [ $(ls $XCURDIRA/aaa_glibc-solibs-*.t?z 2> /dev/null|wc -l) -gt 0 ] ;then
	(
	    cd $XCURDIRA
	    if [ $(ls /var/log/packages/glibc-solibs-*|wc -l) -gt 0 ] ;then
		PAC1=$(ls -t aaa_glibc-solibs-*.t?z|head -1)
		PAC2=$(ls -t aaa_libraries-*.t?z|head -1)
		upgradepkg glibc-solibs%$PAC1
		upgradepkg aaa_elflibs%$PAC2
	    else
		slackpkg upgrade aaa_glibc-solibs
		slackpkg upgrade aaa_libraries
	    fi
	    cd ../../..
	    [ -d ${SLACKVER} ] && upgradepkg --reinstall --install-new \
					 ${SLACKVER}/aaa_glibc-solibs-*.t?z
	)
    else
	slackpkg upgrade glibc-solibs
	# Upgrade glibc-solibs for multilib.
	[ -d ${SLACKVER} ] && upgradepkg --reinstall --install-new \
				     ${SLACKVER}/glibc-solibs-*.t?z
    fi
}

# Upgrade the Slackware current system.
upgradesys () {
    setconfslackpkg
    echo "update";echo '------------'
    slackpkg update gpg
    slackpkg update
    echo "upgrade slackpkg";echo '------------'
    slackpkg upgrade slackpkg
    setconfslackpkg
    echo "upgrade base";echo '------------'
    slackpkg update
    slackpkg new-config
    echo "Upgrade glibc";echo '------------'
    upgradeglibc
    echo "Upgrade pkgtools and other critical packages"
    echo '------------'
    slackpkg upgrade pkgtools
    slackpkg upgrade tar
    slackpkg upgrade xz
    slackpkg upgrade findutils
    echo "install-new";echo '------------'
    slackpkg install-new
    echo "upgrade-all";echo '------------'
    slackpkg upgrade-all
    echo "clean-system";echo '------------'
    slackpkg clean-system

    if [ $? -ne 0 ] ;then
	rm -f $XTEMPOUT
	which slackpkg 2> $XTEMPMES
	mygt 'Abort : see previous errors.' >> $XTEMPMES
	mygt "Upgrade system not done." >> $XTEMPMES
	XEND=1
    else
        xupmainpac "libxkbcommon-" t?z alien l
        xupmainpac "qt5-[0-9]" t?z alien l
        xupmainpac "qt5-webkit-[0-9]" t?z alien l
        xupmainpac "PyQt-[0-9]" t?z alien l
	xupmainpac "PyQt5-[0-9]" t?z alien l
	removepkg qt5-speech
	myconfig
	mygt "Upgrade system done." >> $XTEMPMES
    fi
}
