#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

xhookopenshot () {
    # Post actions for openshot
    (
	cd packages
	rm -rf python-pillow
	cd openshot
	rm -f frei0r-plugins-1.4-x86_64-2dj.*
	rm -rf python3-certifi
	rm -f python3-certifi-2019.6.16-x86_64-1_SBo.*
	rm -f libopenshot-0.2.5-x86_64-1ponce.*
	rm -f dos2unix-7.4.2-x86_64-2cf.*
	rm -f double-conversion-3.1.7-x86_64-1cf.*
	rm -f potrace-1.16-x86_64-2cf.*
	rm -f gdl-3.40.0-x86_64-1cf.*
	rm -f graphicsmagick-1.3.37-x86_64-1cf.*
	rm -f libvdpau-va-gl-0.4.2-x86_64-1dj.*
    )
    removepkg frei0r-plugins
    removepkg python3-certifi
    removepkg graphicsmagick
    upgradepkg --reinstall $SLACKREPO/$SLACKSUBDIR/l/python-certifi-*.t?z
}

xhookpitivi () {
    # Post actions for pitivi
    rm -rf packages/pitivi/python3-six
    rm -f packages/pitivi/python3-six-*-x86_64-1_SBo.*
    removepkg python3-six
    upgradepkg --reinstall $SLACKREPO/$SLACKSUBDIR/l/python-six-*.t?z
}

xhookdebian () {
    # Post actions for debian
    echo "none" > /dev/null
}

xprepac1 () {
    rm -f packages4/gst-plugins-bad-[0-9]*ponce.*
    rm -f packages*/*-3alien*.*
    rm -f packages/32/*-3alien*.*
    (
	cd packages
	mkdir -p oldjava
	[ $(ls openjdk-*-1alien.* 2> /dev/null|wc -l) -gt 0 ] &&\
	    mv openjdk-*-1alien.* oldjava
	[ $(ls openjdk11-*-1alien.* 2> /dev/null|wc -l) -gt 0 ] &&\
	    mv openjdk11-*-1alien.* oldjava
    )
    removepkg openjdk
    removepkg openjdk11
}

xhookpac1 () {
    # Post actions for packages
    upgradepkg --reinstall $SLACKREPO/$SLACKSUBDIR/ap/linuxdoc-tools-*.t?z
#    upgradepkg --reinstall packages/glibc-*alien.t?z
    removepkg phonon4qt5
    removepkg OpenAL
    removepkg OpenAL-compat32
    (
	cd packages
	rm -f openal-soft-1.*_SBo.tgz
	rm -f *_slonly.*
	rm -f 32/wxPython-2.8.12.1-i486-3dj.*
    )
}

xprepac2 () {
    removepkg fontforge
}

xhookpac2 () {
    # Post actions for packages2
    upgradepkg --reinstall $SLACKREPO/$SLACKSUBDIR/l/oniguruma-*.t?z
    (
	cd packages2
	cp youtube.lua $XLIBDIR/vlc/lua/playlist
	rm -f $XLIBDIR/vlc/lua/playlist/youtube.luac
	rm -f discord-*.tar.gz
	rm -f *_slonly.*
	rm -f valgrind-3.18.1-x86_64-1cf.*
	rm -f jq-1.6-x86_64-2cf.*
	rm -f lua53-5.3.6-x86_64-1cf.*
	rm -f lua-5.4.3-x86_64-1cf.*
	rm -f oniguruma-6.9.2-x86_64-1cf.*
	rm -f guile1.8-1.8.8-x86_64-1dj.*
	rm -f gnome-desktop-3.36.6-x86_64-1dl.*
	rm -f webkitgtk-2.28.4-x86_64-1dl.*
	rm -f libseccomp-2.4.2-x86_64-1dl.*
    )
}

xhookpac3 () {
    # Post actions for packages3
    echo "none" > /dev/null
}

xhookcalibre () {
    # Post actions for packages3
    rm -f calibre-4.15.0-x86_64-1alien.txz.*
}

xhookkde4 () {
    # Post actions for kde4
    # Reput the current one. It has been modified by deps for compilation.
    upgradepkg --reinstall $SLACKREPO/$SLACKSUBDIR/l/sip-*.txz
}

xhookkde4deps () {
    # Post actions for kde4
    # Reput the current one. It has been modified by deps for compilation.
    removepkg attica
}

xhookframew () {
    # Post actions for framew
    echo "none" > /dev/null
}

xhookpac4 () {
    # For H264 and DRM support for Opera.
    if [ -f $XLIBDIR/chromium/libffmpeg.so ] ;then
	if [ -d $XLIBDIR/opera ] ;then
	    mv -f $XLIBDIR/opera/libffmpeg.so $XLIBDIR/opera/libffmpeg.so.bak
	    ln -sf $XLIBDIR/chromium/libffmpeg.so $XLIBDIR/opera
	fi
	if [ -d $XLIBDIR/opera-beta ] ;then
	    mv -f $XLIBDIR/opera-beta/libffmpeg.so \
	       $XLIBDIR/opera-beta/libffmpeg.so.bak
	    ln -sf $XLIBDIR/chromium/libffmpeg.so $XLIBDIR/opera-beta
	fi
    fi
    if [ -f $XLIBDIR/chromium/libwidevinecdm.so ] ;then
	[ -d $XLIBDIR/opera ] && \
	    ln -sf $XLIBDIR/chromium/libwidevinecdm.so $XLIBDIR/opera
	[ -d $XLIBDIR/opera-beta ] && \
	    ln -sf $XLIBDIR/chromium/libwidevinecdm.so $XLIBDIR/opera-beta
    fi

    (
	cd packages4
	rm -f exiftool-12.38-x86_64-1cf.*
	rm -f unrar-6.1.3-x86_64-1cf.*
	rm -f xcftools-1.0.7-x86_64-1dj.*
    )
}

xhooktess () {
    # Post actions for tesseract
    (
	cd packages4/tesseract
	rm -f tesseract-*cf.*
	rm -f leptonica-*cf.*
	rm -f xsane2tess*.pl
	rm -f XSANE2TESS.txt
    )
}

# Some config I always use.
myconfig () {
    if [ -d /etc/profile.d ] ; then
	cp pbslacks/LocaleFR/csh.cshrc /etc
	cp pbslacks/LocaleFR/pbalias.sh /etc/profile.d
	XLANG=$(echo $LANG|cut -d '.' -f1|cut -d '_' -f1)
	if [ "$XLANG" = 'fr' ] ;then
	    cp pbslacks/LocaleFR/lang.* /etc/profile.d
	    KBX11=90-keyboard-layout-evdev.conf
	    [ ! -f /etc/X11/xorg.conf.d/$KBX11 ] && \
		cp pbslacks/LocaleFR/$KBX11 /etc/X11/xorg.conf.d
	fi
    fi
    # Bug with KDE 4 and Pulseaudio.
    cat pbslacks/builds/start-pulseaudio-x11.patch|(cd /usr/bin;patch -f -p0)
}
