#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

# Upgrade with the main stream package.
xupmainpac () {
    pac="$1"
    suf="$2"
    repo="$3"
    grp="$4"
    [ $(ls /var/log/packages/${pac}*-[0-9]$repo 2> /dev/null|wc -l) -eq 1 ] &&\
	upgradepkg slackware64/$grp/${pac}*$suf
}

# Upgradepkg with reinstall if the package date is newer than the installed
# one. I could have recompiled.
upgradedir () {
    xdir="$1"
    (
	cd "$xdir"
	ls *.t?z|while read i;test "$i" != "" ;do
	    upgradepkg --install-new "$i"
	    j=/var/log/packages/$(echo "$i"|sed 's/\.t.z$//')
	    [ "$i" -nt "$j" ] && upgradepkg --reinstall "$i"
	done
    )
}

# Upgrade the Slackware current system.
upgradesys () {
    cp pbslacks/Slackpkg/blacklist /etc/slackpkg
    if [ $ISSYSTEM -eq 1 ] ;then
	cat pbslacks/Slackpkg/slackpkg.conf | \
	    sed "s@CHECKGPG=on@CHECKGPG=off@" \
		> /etc/slackpkg/slackpkg.conf
	cat pbslacks/Slackpkg/mirrors | sed "s@HOMESLACK@${HOMESLACK}@" \
					    > /etc/slackpkg/mirrors
    else
	cp pbslacks/Slackpkg/slackpkg.conf /etc/slackpkg
	cat pbslacks/Slackpkg/mirrors | \
	    sed "s@^.*HOMESLACK.*\$@${SLACKMIR}@" > /etc/slackpkg/mirrors
    fi
    echo "update";echo '------------'
    slackpkg update gpg
    slackpkg update
    echo "upgrade base";echo '------------'
    slackpkg upgrade slackpkg
    slackpkg new-config
    slackpkg upgrade glibc-solibs
    slackpkg upgrade pkgtools
    slackpkg upgrade tar
    slackpkg upgrade xz
    slackpkg upgrade findutils
    echo "install-new";echo '------------'
    slackpkg install-new
    echo "upgrade-all";echo '------------'
    slackpkg upgrade-all
    echo "clean-system";echo '------------'
    slackpkg clean-system

    if [ $? -ne 0 ] ;then
	rm -f $XTEMPOUT
	which slackpkg 2> $XTEMPMES
	mygt 'Abort : see previous errors.' >> $XTEMPMES
	mygt "Upgrade system not done." >> $XTEMPMES
	XEND=1
    else
        xupmainpac "libxkbcommon-" t?z alien l
        xupmainpac "qt5-[0-9]" t?z alien l
        xupmainpac "qt5-webkit-[0-9]" t?z alien l
        xupmainpac "PyQt-[0-9]" t?z alien l
	xupmainpac "PyQt5-[0-9]" t?z alien l
	removepkg qt5-speech
	myconfig
	mygt "Upgrade system done." >> $XTEMPMES
    fi
}
