#! /bin/sh

# Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org)
# Date : 2019
# License : See the LICENSE file in this repository.

. "$(dirname $0)/pbinclude"
. "$(dirname $0)/pbupgradeinc"
. "$(dirname $0)/pbupgradesys"

# For systemnet upgrade. Change mirror if you want.
SLACKMIR='http://nephtys.lip6.fr/pub/linux/distributions/slackware/slackware64-${SLACKVER}/'

xhelp () {
    mygt 'Launch this script in the directory including alreadey cloned slackware64 or slackware64-current.\nIt can be on the bootable slackware install USB stick.\npbslacks should also be there.'|sed 's@\\n@\n@g'
    echo
    echo '  > cd .../Slackware-x64-date'
    echo 'or> cd /run/media/$USER/USBSLACKINS/SlackDVD'
    echo '  > pbslacks/pbupgrade [-new (no system upgrade)]'
    echo '       [-test (test only, no actions)] [-help|-h] [-nodial]'
}

XNEW=
MYUSER=produits
MYGROUP=users

while [ $# -ge 1 ] ;do
    MYARG="$1"
    if [ "$MYARG" = "-new" ] ;then
	XNEW=yes
    elif [ "$MYARG" = "-nodial" ] ;then
	ISDIAL=0
    elif [ "$MYARG" = "-test" ] ;then
	XTEST=1
    elif [ "$MYARG" = "-u" ] ;then
	shift
	MYUSER="$1"
    elif [ "$MYARG" = "-g" ] ;then
	shift
	MYGROUP="$1"
    elif [ "$MYARG" = "-help" -o "$MYARG" = "-h" ] ;then
	xhelp
	exit 0
    fi
    shift
done

XTEMPOUT=$(mktemp -p /tmp -t pbupgradeout.XXXXXX)
XTEMPMES=$(mktemp -p /tmp -t pbupgrademes.XXXXXX)

cleanup () {
    rm -f $XTEMPOUT
    rm -f $XTEMPMES
}

trap 'echo "*** Ctrl-C caught -- aborting operations ***"; cleanup; exit 1' 2 14 15 # trap Ctrl-C and kill

if [ ! -d /boot ] ;then
    mygt "Do the install of the Slackware Linux distribution before :\n-see the doc/SLACKWARE.txt file." |sed 's@\\n@\n@g' > $XTEMPMES
fi

if [ $XTEST -ne 1 ] ;then
    if [ -d slackware64-${SLACKVER} ] ;then
	cd slackware64-${SLACKVER}
    elif [ -d slackwarearm-${SLACKVER} ] ;then
	cd slackwarearm-${SLACKVER}
    fi
    if [ '(' ! -d slackware64 -a ! -d slackware ')' \
	     -o '(' ! -h pbslacks -a ! -d pbslacks ')' ] ;then
	mygt 'slackware64 or pbslacks not found.'> $XTEMPMES
	xhelp >> $XTEMPMES
    fi
fi

if [ -s "$XTEMPMES" ] ;then
    dialog --colors --backtitle 'pbupgrade' --title 'End messages' \
	--msgbox "$(cat $XTEMPMES)" 20 85
    cleanup
    exit 1
fi

DACTION=$(mygt 'Actions which were done')

if [ $XTEST -ne 1 ] ;then
    if [ ! $UID = 0 ]; then
        mygt 'This script must be done as root. Exit.' > $XTEMPMES
        dialog --colors --backtitle 'pbupgrade' --title "$DACTION" \
	    --msgbox "$(cat $XTEMPMES)" 20 80
	cleanup
	exit 1
    fi
fi

MYPWD=$(pwd)
HOMESLACK="$MYPWD"

if [ "$XNEW" = 'yes' ] ;then
    XUPSYSTEM=off
else
    XUPSYSTEM=on
fi

xmaster () {
    defitem=$1;shift
    xsel1=$1;shift;xsel2=$1;shift;xsel3=$1;shift;xsel4=$1;shift;xsel5=$1;shift
    xsel6=$1;shift;xsel7=$1;shift;xsel8=$1;shift;xsdeb=$1;shift;xsel9=$1;shift
    xsgdm=$1;shift;xsel10=$1;shift;xselpi=$1;shift;xsel11=$1;shift
    xsel12=$1;shift;xslmms=$1;shift;xsel13=$1;shift;xsel14=$1;shift;xsel24=$1
    pactit=$(mygt 'Main menu')
    pactit="pbupgrade ($PBARCH) : $pactit"
    dialog --colors --backtitle "pbupgrade ($PBARCH)" --title "$pactit" \
	--default-item $defitem --defaultno \
	--separate-output --item-help --help-button --help-status --checklist \
	"$(mygt 'Choose your actions below after you have launch the \Zbpbaspire*\ZB script')" 0 110 19 \
	system "$(mygt 'Sync/Upgrade system to the last fetched current Slackware')" $xsel1 system \
	systemnet "$(mygt 'Sync/Upgrade system to the last current Slackware on the internet')" $xsel2 systemnet \
	compat32 "$(mygt 'Install/Upgrade the 32 bits compatible mode')" $xsel3 compat32 \
	mozilla "$(mygt 'Install/Upgrade the Firefox and Thunderbird softwares')" $xsel4 mozilla \
	packages "$(mygt 'Install/Upgrade the packages set of software')" $xsel5 packages \
	packages2 "$(mygt 'Install/Upgrade the packages2 set of software')" $xsel6 packages2 \
	packages3 "$(mygt 'Install/Upgrade the packages3 set of software')" $xsel7 packages3 \
	packages4 "$(mygt 'Install/Upgrade the packages4 set of software')" $xsel8 packages4 \
	debian "$(mygt 'Install/Upgrade Debian binary packages')" $xsdeb debian \
	frameworks "$(mygt 'Install/Upgrade KDE4 and the KDE5 frameworks libraries')" $xsel9 frameworks \
	gdm "$(mygt 'Install/Upgrade GDM from Gnome 2 desktop manager')" $xsgdm gdm \
	openshot "$(mygt 'Install/Upgrade the Openshot software')" $xsel10 openshot \
	pitivi "$(mygt 'Install/Upgrade the Pitivi software')" $xselpi pitivi \
	audacity "$(mygt 'Install/Upgrade the Audacity software')" $xsel11 audacity \
	ardour "$(mygt 'Install/Upgrade the Ardour software')" $xsel12 ardour \
	lmms "$(mygt 'Install/Upgrade the LMMS software')" $xslmms lmms \
	tesseract4 "$(mygt 'Install/Upgrade the Tesseract version 4 software')" $xsel13 tesseract4 \
	bumblebee "$(mygt 'Install/Upgrade the Bumblebee support of your second NVIDIA graphic card')" $xsel14 bumblebee \
    	bootload "$(mygt 'Upgrade boot loader.')" $xsel24 bootload
}

xpacaide () {
    packages="$1"
    pacaide="Upgrade the $packages set of tools :"
    ls -1 "$packages/"*.t?z > $XTEMPMES
    while read j;test "$j" != "" ;do
	pacaide="${pacaide}\n$j"
    done < $XTEMPMES
    rm -f $XTEMPMES
}

xpacaide_add () {
    packages="$1"
    ls -1 "$packages/"*.t?z > $XTEMPMES
    while read j;test "$j" != "" ;do
	pacaide="${pacaide}\n$j"
    done < $XTEMPMES
    rm -f $XTEMPMES
}

xframe=on
[ $(ls /var/log/packages/plasma-desktop-*[0-9]* 2> /dev/null|wc -l) -ge 1 ] && \
    xframe=off
xother=on
[ $PBARCH = arm ] && xother=off
xdebian=off
[ $PBARCH = arm ] && xdebian=on
xsel="$XUPSYSTEM off $xother $xother $xother $xother $xother \
$xother $xdebian $xframe $xother $xother $xother $xother $xother $xother \
$xother off off"
ditem=system
bclaide=1

while [ $bclaide -eq 1 ] ;do
    xmaster $ditem $xsel 2> $XTEMPOUT
    bclaide=$(cat $XTEMPOUT|grep '^HELP'|wc -l)
    if [ $bclaide -eq 1 ] ;then
	xitem="$(cat $XTEMPOUT|grep '^HELP'|cut -d ' ' -f2)"
	xsel=
	for i in system systemnet compat32 mozilla packages packages2 packages3 \
			packages4 debian frameworks gdm openshot pitivi audacity \
			ardour lmms tesseract4 bumblebee bootload ;do
	  if [ $(grep "^$i$" "$XTEMPOUT"|wc -l) -eq 1 ] ;then
	      xsel="$xsel on"
	  else
	      xsel="$xsel off"
	  fi
	done
	ditem=$xitem;bclaide=1;pacaide=
	if [ "$xitem" = system ] ;then
	    pacaide=$(mygt 'Upgrade your Slackware system with the last current fetched.\nUses Slackpkg.')
	elif [ "$xitem" = systemnet ] ;then
	    pacaide=$(mygt 'Upgrade your Slackware system with the last current on the internet.\nUses Slackpkg.')
	elif [ "$xitem" = compat32 ] ;then
	    pacaide=$(mygt 'Upgrade the Alien Bob 32 bits compatible mode.')
	elif [ "$xitem" = mozilla ] ;then
	    pacaide=$(mygt 'Upgrade the Firefox and Thunderbird products.\nThey should be downloaded and put in the packages/Mozilla directory before.')
	elif [ "$(echo "$xitem"|cut -c1-8)" = packages ] ;then
	    xpacaide "$xitem"
	elif [ "$xitem" = frameworks ] ;then
	    xpacaide kde4/kde
	    xpacaide_add kde4/deps
	    xpacaide_add kde4/other
	    xpacaide_add kde4/kdeother
	    xpacaide_add kde5/frameworks
	    xpacaide_add kde5/deps
	elif [ "$xitem" = gdm ] ;then
	    xpacaide gdm
	elif [ "$xitem" = debian ] ;then
	    xpacaide debian
	elif [ "$xitem" = openshot ] ;then
	    xpacaide packages/openshot
	elif [ "$xitem" = pitivi ] ;then
	    xpacaide packages/pitivi
	elif [ "$xitem" = audacity ] ;then
	    xpacaide packages4/audacity
	elif [ "$xitem" = ardour ] ;then
	    xpacaide packages4/ardour
	elif [ "$xitem" = lmms ] ;then
	    xpacaide packages4/lmms
	elif [ "$xitem" = tesseract4 ] ;then
	    xpacaide packages4/tesseract4
	elif [ "$xitem" = bumblebee ] ;then
	    pacaide=$(mygt 'Upgrade your Bumblebee packages if they are in sync with the upgraded Slackware.\nDone on another machine for exemple.')
	elif [ "$xitem" = bootload ] ;then
	    pacaide=$(mygt "Upgrade your boot loader only if you upgrade your system and not the bootloader.") 
	fi
	dialog --colors --backtitle 'pbupgrade' --title "$xitem" \
	    --msgbox "$pacaide" 20 90
    fi
done

XEND=0

ISSYSTEM="$(cat $XTEMPOUT|grep '^system$'|wc -l)"
ISSYSNET="$(cat $XTEMPOUT|grep '^systemnet$'|wc -l)"
ISCOMPAT="$(cat $XTEMPOUT|grep '^compat32$'|wc -l)"
ISMOZ="$(cat $XTEMPOUT|grep '^mozilla$'|wc -l)"
ISPACK="$(cat $XTEMPOUT|grep '^packages$'|wc -l)"
ISPACK2="$(cat $XTEMPOUT|grep '^packages2$'|wc -l)"
ISPACK3="$(cat $XTEMPOUT|grep '^packages3$'|wc -l)"
ISPACK4="$(cat $XTEMPOUT|grep '^packages4$'|wc -l)"
ISFRAMEW="$(cat $XTEMPOUT|grep '^frameworks$'|wc -l)"
ISGDM="$(cat $XTEMPOUT|grep '^gdm$'|wc -l)"
ISDEBIAN="$(cat $XTEMPOUT|grep '^debian$'|wc -l)"
ISOPENSHOT="$(cat $XTEMPOUT|grep '^openshot$'|wc -l)"
ISPITIVI="$(cat $XTEMPOUT|grep '^pitivi$'|wc -l)"
ISAUDACITY="$(cat $XTEMPOUT|grep '^audacity$'|wc -l)"
ISARDOUR="$(cat $XTEMPOUT|grep '^ardour$'|wc -l)"
ISLMMS="$(cat $XTEMPOUT|grep '^lmms$'|wc -l)"
ISTESS="$(cat $XTEMPOUT|grep '^tesseract4$'|wc -l)"
ISBUMBLE="$(cat $XTEMPOUT|grep '^bumblebee$'|wc -l)"

ISBOOTLOAD="$(cat $XTEMPOUT|grep '^bootload$'|wc -l)"

if [ $ISSYSTEM -eq 1 -o $ISSYSNET -eq 1 ] ;then
    if [ $XTEST -ne 1 ] ;then
	upgradesys
    else
	mygt "Upgrade system done." >> $XTEMPMES
    fi
fi
if [ $XEND -eq 0 ] ;then
    if [ $ISCOMPAT -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    if [ $(ls ${SLACKVER}/aaa_glibc-solibs-*.t?z 2> /dev/null|wc -l) -gt 0 ]
	    then
		rm -f ${SLACKVER}/glibc-solibs-*
		rm -f ${SLACKVER}/slackware64-compat32/a-compat32/aaa_elflibs-compat32-*
	    fi
	    upgradepkg --reinstall --install-new ${SLACKVER}/*.t?z
	    upgradepkg --install-new ${SLACKVER}/slackware64-compat32/*/*.t?z
	fi
	mygt "Upgrade Alien Bob multilib done." >> $XTEMPMES
    fi
    if [ $ISMOZ -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    $HOMESLACK/pbslacks/pbupgrademoz
	fi
	mygt "Upgrade Mozilla done." >> $XTEMPMES
    fi
    if [ $ISPACK -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages
	    upgradedir packages/compat32
	    xhookpac1
	fi
	mygt "Upgrade packages done." >> $XTEMPMES
    fi
    if [ $ISPACK2 -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages2
	    xhookpac2
	fi
	mygt "Upgrade packages2 done." >> $XTEMPMES
    fi
    if [ $ISPACK3 -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages3
	    xhookpac3
	fi
	mygt "Upgrade packages3 done." >> $XTEMPMES
    fi
    if [ $ISPACK4 -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages4
	    xhookpac4
	fi
	mygt "Upgrade packages4 done." >> $XTEMPMES
    fi
    if [ $ISDEBIAN -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir debian
	    xhookdebian
	fi
	mygt "Upgrade debian binary packages done." >> $XTEMPMES
    fi
    if [ $ISFRAMEW -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir kde4/deps
	    upgradedir kde4/other
	    upgradedir kde4/kdeother
	    xhookkde4deps
	    upgradedir kde4/kde
	    xhookkde4
	    upgradedir kde5/deps
	    upgradedir kde5/frameworks
	    xhookframew
	fi
	mygt "Upgrade KDE4 and KDE5 frameworks done." >> $XTEMPMES
    fi
    if [ $ISGDM -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir gdm
	fi
	mygt "Upgrade GDM desktop manager done." >> $XTEMPMES
    fi
    if [ $ISOPENSHOT -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages/openshot
	    xhookopenshot
	fi
	mygt "Upgrade openshot done." >> $XTEMPMES
    fi
    if [ $ISPITIVI -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages/pitivi
	    xhookpitivi
	fi
	mygt "Upgrade pitivi done." >> $XTEMPMES
    fi
    if [ $ISAUDACITY -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages4/audacity
	fi
	mygt "Upgrade audacity done." >> $XTEMPMES
    fi
    if [ $ISARDOUR -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages4/ardour
	fi
	mygt "Upgrade ardour done." >> $XTEMPMES
    fi
    if [ $ISLMMS -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages4/lmms
	fi
	mygt "Upgrade lmms done." >> $XTEMPMES
    fi
    if [ $ISTESS -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    upgradedir packages4/tesseract4
	    xhooktess
	fi
	mygt "Upgrade tesseract4 done." >> $XTEMPMES
    fi
    if [ $ISBUMBLE -eq 1 ] ;then
	if [ $XTEST -ne 1 ] ;then
	    $HOMESLACK/pbslacks/pbupgradebumblebee
	fi
	mygt "Upgrade Bumblebee done." >> $XTEMPMES
    fi
    if [ $ISBOOTLOAD -eq 1 -a "$PBARCH" = x64 ] ;then
	mygt "Updating bootloader asked." >> $XTEMPMES
    fi
fi

if [ ! -f "$XTEMPMES" -o ! -s "$XTEMPMES" ] ;then
    mygt "No action was demanded. Exit." > $XTEMPMES
    XEND=1
fi

dialog --colors --backtitle 'pbupgrade' --title "$DACTION" \
       --msgbox "$(cat $XTEMPMES)" 20 80
cleanup

if [ $XEND -eq 1 ] ;then
    exit 0
fi

if [ '(' $ISSYSTEM -eq 1 -o $ISBOOTLOAD -eq 1 ')' -a "$PBARCH" = x64 ] ;then
# Only if system was modified
    if [ -d /boot/efi/EFI/Slackware ] ;then
	xitem=elilo
    elif [ -f /boot/grub/grub.cfg ] ;then
	xitem=grub
    elif [ -f /etc/lilo.conf ] ;then
	xitem=lilo
    elif [ -f /syslinux.cfg ] ;then
	xitem=syslinux
    else
	xitem=none
    fi
    pactit=$(mygt 'Bootloader menu')
    pactxt=$(mygt 'We have detected the bootloader below. Cancel if it is not true.\nIn this last case, you should recreate the config of your bootloader before reboot. Else you will have to boot from another media as a DVD or an USB stick and rerun the install of your bootloader.')
    pacnone=$(mygt 'No bootloader detected. Reconfigure your bootloader before reboot.')
    dialog --colors --backtitle 'pbupgrade' --title "$pactit" \
	--default-item $xitem --menu "$pactxt" 15 80 5 \
	elilo 'Boot Elilo : /boot/efi/EFI/Slackware' \
	grub 'Boot Grub : /boot/grub/grub.cfg' \
	lilo 'Boot Lilo : /etc/lilo.conf' \
	syslinux 'Boot Syslinux : /syslinux.cfg' \
	none "$pacnone"\
	2> $XTEMPOUT
    xitem=$(cat $XTEMPOUT)

    xmes1 () {
	mygt "\ZbThe boot loader was not upgraded.\ZB\nIf lilo is installed, launch : \Z3/sbin/lilo\Zn\nIf Grub is installed, launch : \Z3grub-mkconfig -o /boot/grub/grub.cfg\Zn\nIf Syslinux is installed, launch : \Z3syslinux BOOTDEVICE\Zn\nIf Boot UEFI ELILO is installed, do :\n  \Z3cp /boot/vmlinuz /boot/initrd.gz /boot/efi/EFI/Slackware\Zn\n\n\ZbOr rerun your other favorite bootloader install procedure before rebooting.\ZB"
    }

    if [ "$xitem" = elilo -a -d /boot/efi/EFI/Slackware ] ;then
	mygt "Elilo upgraded : Files vmlinuz et initrd.gz copied in \Z3/boot/efi/EFI/Slackware\Zn" >> $XTEMPMES
	if [ $XTEST -ne 1 ] ;then
	    cp /boot/vmlinuz /boot/initrd.gz /boot/efi/EFI/Slackware
	fi
    elif [ "$xitem" = grub -a -f /boot/grub/grub.cfg ] ;then
	mygt "Grub upgraded : \Z3grub-mkconfig\Zn relaunched.\n\Z1Look if there are error messages below\Zn." >> $XTEMPMES
	if [ $XTEST -ne 1 ] ;then
	    grub-mkconfig -o /boot/grub/grub.cfg 2>> $XTEMPMES
	fi
    elif [ "$xitem" = lilo -a -f /etc/lilo.conf ] ;then
	mygt "Lilo upgraded with \Z3/sbin/lilo\Zn.\n\Z1Look if there are error messages below\Zn." >> $XTEMPMES
	if [ $XTEST -ne 1 ] ;then
	    /sbin/lilo 2>> $XTEMPMES
	fi
    elif [ "$xitem" = syslinux -a -f /syslinux.cfg ] ;then
	mygt "Look at \Z3/syslinux.cfg\Zn and rerun \Z3syslinux\Zn on your boot partition if some path have changed." >> $XTEMPMES
    else
	xmes1 >> $XTEMPMES
    fi

    if [ -f "$XTEMPMES" ] ;then
	dialog --colors --backtitle 'pbupgrade' --title 'Bootloader upgraded' \
	    --msgbox "$(cat $XTEMPMES)" 20 80
    fi

    cleanup
fi

if [ "$XNEW" != 'yes' ] ;then
    XBOOTMES=$(mygt ' (\Z1be sure to have upgraded the bootloader before\Zn)')
else
    XBOOTMES=
fi

xend () {
    emygt "Reboot the host\${XBOOTMES}.\n\n\ZbThen do if not already done on an already upgraded target :\ZB\nSelect '\Z3recreate\Zn' in the above menu after launching this script again.\n or do> \Z3pbslacks/pbcompilepost\Zn\n\n\ZbIf your host is a dual graphic card laptop with a NVIDIA card :\ZB\n  \Z4Do either :\Zn\n    Select '\Z3recreatebumblebee\Zn' in the above menu after launching this script again.\n    or do> \Z3pbslacks/pbcompilebumblebee\Zn\n  \Z4Or do only if already done on an upgraded target :\Zn\n    Select '\Z3bumblebee\Zn' in the above menu after launching this script again.\n    or do> \Z3pbslacks/pbupgradebumblebee\Zn"
}

xend >> $XTEMPMES

if [ -f "$XTEMPMES" ] ;then
    dialog --colors --backtitle 'pbupgrade' --title 'End messages' \
	--msgbox "$(cat $XTEMPMES)" 20 85
fi
rm -f $XTEMPMES
